### ISSUE TITLE
Usage of PixelUtil causes crash on the app start

### ISSUE THREAD

**Issue by sercand** [software-mansion/react-native-screens#1008]
## Description

We got lots of following crash on our app at production:

```
Caused by java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference
       at android.util.TypedValue.applyDimension(TypedValue.java:391)
       at com.facebook.react.uimanager.PixelUtil.toPixelFromDIP(PixelUtil.java:18)
       at com.swmansion.rnscreens.ScreenStackFragment.<clinit>(ScreenStackFragment.java:64)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
```

It is caused by usage of [PixeUtil](https://github.com/software-mansion/react-native-screens/blob/6bc0b7dec49597d70b2a6f7bef7429836441e8e1/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java#L64) to assign static variable at start.

My [commit](https://github.com/sercand/react-native-screens/commit/b028a6936659b43e5c5c6817a142a8d3d1a3da6a) may fix this. Since I don't know how to reproduce this on my test devices, I will test on production app and will open a pull request. 

## Package versions

- React: 16.9.0, 17.0.1
- React Native: 0.63.2, 0.64.2
- React Native Screens: 3.4

**Comment by carloscastrodev** [comment]
Experiencing the same behaviour in production. Did your commit work?

**Comment by sercand** [comment]
@carloscastrodev Yes my commit worked and we no longer see the crash on the production. I am going to open MR for this.

**Comment by WoLewicki** [comment]
@carloscastrodev @sercand can you provide a reproduction of the crash? We would like to avoid merging PR without a reproduction of the problem it fixes.

**Comment by WoLewicki** [comment]
Also, did you try setting the shadow to hidden/shown to check if it works when called only when necessary?

**Comment by sercand** [comment]
@WoLewicki I don't know to reproduce the crash. The app just crashes on start before loading any screen. It happens on different android versions and different vendors randomly. I tested it on production because I don't know to reproduce it and we no longer see the crash.

Our apps don't use toolbar and I will check it later to confirm if it is still working.

**Comment by sercand** [comment]
@WoLewicki PR doesn't affect the changing shadow hidden/shown setting. I believe we can merge the PR.
