### ISSUE TITLE
Crash when swapping between modal modes

### ISSUE THREAD

**Issue by trajano** [software-mansion/react-native-screens#1023]
## Description

I was testing the modal functionality of React Native Screens and trying out three different configurations.  Individually they work, but if you open-dismiss-open-dismiss-open with a couple of seconds it crashes the app.

```
    <Stack.Screen
      name="Modal"
      component={ModalScreen}
      options={{ stackPresentation: "modal" }}
    />
    <Stack.Screen
      name="TransparentModal"
      component={ModalScreen}
      options={{ stackPresentation: "transparentModal" }}
    />
    <Stack.Screen
      name="FullScreenModal"
      component={ModalScreen}
      options={{ stackPresentation: "push" }}
    />
```

### Logcat

```
2021-07-21 21:06:18.207 9207-9207/host.exp.exponent D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2021-07-21 21:06:18.208 9207-9207/host.exp.exponent E/AndroidRuntime: FATAL EXCEPTION: main
    Process: host.exp.exponent, PID: 9207
    java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.View.getAlpha()' on a null object reference
        at androidx.fragment.app.d0$e$c.h(SpecialEffectsController.java:1)
        at androidx.fragment.app.c.f(DefaultSpecialEffectsController.java:2)
        at androidx.fragment.app.d0.g(SpecialEffectsController.java:21)
        at androidx.fragment.app.m.f0(FragmentManager.java:40)
        at androidx.fragment.app.m.k1(FragmentManager.java:11)
        at androidx.fragment.app.m.c0(FragmentManager.java:4)
        at androidx.fragment.app.m$g.run(FragmentManager.java:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-07-21 21:06:18.218 527-1460/system_process W/ActivityTaskManager:   Force finishing activity host.exp.exponent/.experience.HomeActivity
2021-07-21 21:06:18.225 527-1460/system_process W/ActivityTaskManager:   Force finishing activity host.exp.exponent/.experience.ExperienceActivity
2021-07-21 21:06:18.273 9207-9207/host.exp.exponent I/Process: Sending signal. PID: 9207 SIG: 9
```

## Steps To Reproduce

1. On Expo Go open up [the snack](https://snack.expo.dev/@trajano/multi-tab-navigation-with-refresh) on Android emulator (I don't have a real device to confirm this)
2. Open a modal then close the modal
3. Open a modal then close the modal
4. Open a modal ... usually by now the app crashes, even the snack Android emulator crashes.

### Expected behavior

Does not crash

### Actual behavior

VM crash

## Snack or minimal code example

https://snack.expo.dev/@trajano/multi-tab-navigation-with-refresh

## Package versions
{
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "react-native-screens": "~3.4.0",
    "@react-navigation/stack": "^5.14.5",
    "react-native-reanimated": "~2.2.0",
    "@react-navigation/native": "^5.9.4",
    "react-native-gesture-handler": "~1.10.2",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native-stack": "*",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens/native-stack": "~3.4.0",
    "@react-native-community/masked-view": "0.1.10"
  }
}

**Comment by trajano** [comment]
It may be an OS issue https://issuetracker.google.com/issues/183634730?pli=1 but the question would be how do you work around this?

**Comment by WoLewicki** [comment]
From the issue tracker you send, it seems that it was an internal issue and it is solved by now. I am not sure if we can do anything about it in the library. Can we close the issue then?

**Comment by trajano** [comment]
Not sure if it is solved, last I checked it is still failing on Android.  The workaround was to just avoid the native stack navigator and use the non-native stack navigator on Android using a .android.tsx variant.  I'll close it for now since I don't know if anyone else is having the same issue, at least there's a workaround available even if we lose the "native"
