### ISSUE TITLE
[3.6.0] and [3.7.0] e2e fail on our TravisCI for a reason unknown (android)

### ISSUE THREAD

**Issue by Overtorment** [software-mansion/react-native-screens#1131]
## Description

We have tried updating to 3.6.0 & 3.7.0, but our detox e2e CI starts failing on Travis (android, Linux-based). It feels like the app either hangs, either dies and takes an emulator with it. 
Weird thing is that we have the same test suite set up on GithubActions (android, macOS-based) and it works with no issues there.

Our Travi e2e CI setup config is rather hacky (https://github.com/BlueWallet/BlueWallet/blob/master/.travis.yml) and we are thinking of dropping it since we have the same thing running on GithubActions successfully, but maybe this issue is something worth looking at by `react-native-screens` developers.

Full CI logs: 

* https://app.travis-ci.com/github/BlueWallet/BlueWallet/builds/237586313
* https://app.travis-ci.com/github/BlueWallet/BlueWallet/builds/237505123

```
detox[11307] INFO:  BlueWallet UI Tests: can create wallet, reload app and it persists. then go to receive screen, set custom amount and label. Dismiss modal and go to WalletsList. [OK]
detox[11307] INFO:  BlueWallet UI Tests: can encrypt storage, with plausible deniability
emulator: ERROR: detected a hanging thread 'QEMU2 main loop'. No response for 15768 ms
emulator: ERROR: detected a hanging thread 'QEMU2 CPU0 thread'. No response for 18249 ms
emulator: ERROR: detected a hanging thread 'QEMU2 CPU1 thread'. No response for 18611 ms
emulator: ERROR: detected a hanging thread 'QEMU2 CPU1 thread'. No response for 15678 ms
emulator: ERROR: detected a hanging thread 'QEMU2 CPU0 thread'. No response for 15347 ms
emulator: ERROR: detected a hanging thread 'QEMU2 CPU1 thread'. No response for 17708 ms
detox[11307] WARN:  [APP_NONRESPONSIVE] Application nonresponsiveness detected!
On Android, this could imply an ANR alert, which evidently causes tests to fail.
Here's the native main-thread stacktrace from the device, to help you out (refer to device logs for the complete thread dump):
com.github.anrwatchdog.ANRError: Application Not Responding for at least 5000 ms.
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
	at android.view.ThreadedRenderer.nSyncAndDrawFrame(Native Method)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:823)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
detox[11095] INFO:  BlueWallet UI Tests: can create wallet, reload app and it persists. then go to receive screen, set custom amount and label. Dismiss modal and go to WalletsList. [OK]
detox[11095] INFO:  BlueWallet UI Tests: can encrypt storage, with plausible deniability
emulator: ERROR: detected a hanging thread 'QEMU2 CPU0 thread'. No response for 15774 ms
emulator: ERROR: detected a hanging thread 'QEMU2 CPU1 thread'. No response for 22308 ms
emulator: ERROR: detected a hanging thread 'QEMU2 main loop'. No response for 21398 ms
emulator: ERROR: detected a hanging thread 'QEMU2 CPU0 thread'. No response for 22816 ms
detox[11095] INFO:  BlueWallet UI Tests: can encrypt storage, with plausible deniability [FAIL]
detox[11095] INFO:  BlueWallet UI Tests: can encrypt storage, and decrypt storage works
detox[11095] ERROR: [EXEC_FAIL, #126] ""/home/travis/android-sdk/platform-tools/adb" -s emulator-5554 reverse --remove tcp:42981" failed with error = ChildProcessError: Command failed: "/home/travis/android-sdk/platform-tools/adb" -s emulator-5554 reverse --remove tcp:42981
adb: error: device 'emulator-5554' not found
 `"/home/travis/android-sdk/platform-tools/adb" -s emulator-5554 reverse --remove tcp:42981` (exited with error code 1) (code=1), stdout and stderr:
detox[11095] ERROR: [EXEC_FAIL, #126] 
detox[11095] ERROR: [EXEC_FAIL, #126] adb: error: device 'emulator-5554' not found
detox[11095] INFO:  BlueWallet UI Tests: can encrypt storage, and decrypt storage works [FAIL]
```

## Steps To Reproduce

1. ???

## Package versions

- React: `17.0.1`
- React Native: `0.64.2`
- React Native Screens: [3.6.0] and [3.7.0]

**Comment by kacperkapusciak** [comment]
Hi @Overtorment,
First, thanks for submitting an issue! 🙌  

You guys have a quite complicated setup with many dependencies - without a simplified reproduction, there's hardly anything we can tell. And when it works on one provider but not on the other doesn't help with this. I can't see anything clearly screens-related in the stack trace. It can be cache, it can be a clash with another dependency, it can be something provided related - I have no clue.

I'll close this issue for now but if you have a bit more tangible example/repro/steps I'll gladly reopen it.

Cheers

**Comment by Overtorment** [comment]
Fair enough. Thanks!
