### ISSUE TITLE
Android app crashed when navigating from react fragment to native fragment

### ISSUE THREAD

**Issue by gilangFaras** [software-mansion/react-native-screens#1136]
## Description

I have a closed repository in which I integrate React Native with Android Native. I put the react native component inside a fragment and use it for a bottom tab navigation screen. The bottom tab was made in native.
So whenever I try to navigate after the react fragment is loaded, the app will crash.
Navigation between tabs aside from the one with react fragment works fine.

I also put a react native screen in another place, not in a fragment because it's not connected directly to the bottom tab navigation. That screen works fine and doesn't cause any crash.
So I assume the problem is within the fragment. I'm not too familiar with native android development so I was having a difficulty in this.

## Steps To Reproduce

1. The Main screen which has bottom tab navigation with react fragment on one of its tab
2. Navigate to the tab with react fragment and load the rn component
3. Click on other tabs, the app crashed

### Expected behavior
Other native fragment will show according to clicked the bottom tab

### Actual behavior
App crashed (only if the rn screen is loaded and navigate to other tab)
Here's the error
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1778)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1814)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
        at com.swmansion.rnscreens.ScreenContainer.removeMyFragments(ScreenContainer.kt:219)
        at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow(ScreenContainer.kt:231)
        at com.swmansion.rnscreens.ScreenStack.onDetachedFromWindow(ScreenStack.kt:81)
        at android.view.View.dispatchDetachedFromWindow(View.java:19607)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3814)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3806)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3806)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5431)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5402)
        at android.view.ViewGroup.removeView(ViewGroup.java:5333)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1250)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
 ```

## Package versions

- React: 17.0.1
- React Native: 0.64.0
- React Native Screens: 3.7.2
- React Navigation: 6.0.2

**Comment by kacperkapusciak** [comment]
Hi @gilangFaras,
Can you please provide a minimal complete reproducible code sample? With this, I mean a small snippet that reproduces your issue in an empty repo. Please see [this guide](https://stackoverflow.com/help/minimal-reproducible-example).

Cheers

**Comment by WoLewicki** [comment]
@gilangFaras Does the native fragment use `commitNow` or `commit`? From the stack trace it seems like the `ScreenStack`, which means `native-stack`, is being detached from window and tries to remove its fragments while another transaction is ongoing, probably the native fragment's one.

**Comment by alexco2** [comment]
Could it be related to this bug? https://github.com/callstack/react-native-pager-view/issues/440
It only happens when using NativeStackNavigator, so I´m thinking it might be a react-native-screen issue. The error message is different though.

**Comment by WoLewicki** [comment]
@alexco2 the stack trace does not provide any clue that it can be related to `react-native-screens`, but there might be some collisions between the logic of those components that I am unaware of.

**Comment by alexco2** [comment]
Thank you for checking. I thought since it just happens when using NativeStackNavigstor from react-navigation, and the crash happening when navigating back, it might come from the same cause.

**Comment by luislukas** [comment]
@WoLewicki @alexco2 - I can provide more details about this issue since is exactly the same as I opened here: https://github.com/software-mansion/react-native-screens/issues/819
I don't know the set up that @gilangFaras has at the moment but I can explain ours. 
* We use Android navigation components as described here: https://developer.android.com/guide/navigation/navigation-getting-started
* We also use react native through a `Fragment`, rather than an `Activity`. Inside our `Fragment` we have a `ReactDelegate(activity, getReactNativeHost(), COMPONENT_NAME, launchOptions)`, then we do `ReactDelegate.loadApp()`, `mReactDelegate?.reactRootView` in the `onCreateView` etc.
* The crash reproduces 100% of the time when React Native Screens are enabled (in our production at the moment we have to disabled them) AND there is a native navigation happening that ends up revealing the `Fragment` with react native loaded.
* The stack trace points to: `at com.swmansion.rnscreens.ScreenContainer.removeMyFragments(ScreenContainer.kt:216)` which does `transaction.commitNowAllowingStateLoss()`. Swapping that for `commit()` or `commitNow()` has the same crash. Removing that line ends up in a crash in `at com.swmansion.rnscreens.ScreenContainer.removeMyFragments(ScreenContainer.kt:229)`.
* If we remove the above lines, ends up in react views not being populated, I'm guessing because they can't recover and populate the view.

What I think is happening is that the native navigation done with the navigation components, uses the `FragmentManager` under the hood. At some point, this navigation finishes committing the transactions. The react native screens tries to do the same but there are no pending transactions because all has been executed.
My line of investigation at the moment is see if rather than pass `FragmentManager` from the `Activity` here `setFragmentManager(context.supportFragmentManager)` ie `ScreenContainer.kt:170` I can find a way to use `childFragmentManager` form the `Fragment` holding the react native part.

I'll try to come up with a simple project showcasing this peculiar architecture.

**Comment by WoLewicki** [comment]
@luislukas please create a new issue with all the information and reproduction needed.

**Comment by luislukas** [comment]
@WoLewicki Thanks - Is done here: https://github.com/software-mansion/react-native-screens/issues/1506

**Comment by WoLewicki** [comment]
Oh sorry, I missed it 😅
