### ISSUE TITLE
ScreenStack throws fragment exception from pushing screen

### ISSUE THREAD

**Issue by Kudo** [software-mansion/react-native-screens#1138]
## Description

Pushing screen in [ScreenStack example](https://github.com/software-mansion/react-native-screens/blob/2.18.1/Example/nativeStack.js) gets Android fragment exception.
This issue did not happen to react-native-screens@3.6.0

Stacktrace as following:

```
    unknown:ReactNative  E  Exception in native call
                         E  java.lang.IllegalStateException: This transaction is already being added to the back stack
                         E      at androidx.fragment.app.FragmentTransaction.disallowAddToBackStack(FragmentTransaction.java:679)
                         E      at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:302)
                         E      at com.swmansion.rnscreens.ScreenStack.setupBackHandlerIfNeeded(ScreenStack.kt:340)
                         E      at com.swmansion.rnscreens.ScreenStack.access$setupBackHandlerIfNeeded(ScreenStack.kt:17)
                         E      at com.swmansion.rnscreens.ScreenStack$mLifecycleCallbacks$1.onFragmentResumed(ScreenStack.kt:34)
                         E      at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentResumed(FragmentLifecycleCallbacksDispatcher.java:207)
                         E      at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:374)
                         E      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
                         E      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
                         E      at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
                         E      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
                         E      at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2007)
                         E      at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
                         E      at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
                         E      at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
                         E      at com.swmansion.rnscreens.ScreenStack.onUpdate(ScreenStack.kt:280)
                         E      at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.kt:294)
                         E      at com.swmansion.rnscreens.ScreensShadowNode.onBeforeLayout$lambda-0(ScreensShadowNode.kt:15)
                         E      at com.swmansion.rnscreens.ScreensShadowNode.lambda$OP8O-3NTREBtSmNbm5uT9SWXiEQ(Unknown Source:0)
                         E      at com.swmansion.rnscreens.-$$Lambda$ScreensShadowNode$OP8O-3NTREBtSmNbm5uT9SWXiEQ.execute(Unknown Source:2)
                         E      at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:573)
                         E      at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
                         E      at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
                         E      at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
                         E      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1079)
                         E      at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
                         E      at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
                         E      at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
                         E      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1000)
                         E      at android.view.Choreographer.doCallbacks(Choreographer.java:823)
                         E      at android.view.Choreographer.doFrame(Choreographer.java:754)
                         E      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:987)
                         E      at android.os.Handler.handleCallback(Handler.java:938)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loopOnce(Looper.java:201)
                         E      at android.os.Looper.loop(Looper.java:288)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7858)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
```

### Screenshots

<img width="300" src="https://user-images.githubusercontent.com/46429/133914909-a917c304-afa4-42d4-9cee-b791c684b3e2.png" />

## Steps To Reproduce

```sh
$ npx react-native init RN064 --version 0.64
$ cd RN064
$ yarn add 'react-native-screens@3.7.2'
$ wget https://raw.githubusercontent.com/software-mansion/react-native-screens/2.18.1/Example/nativeStack.js -O App.js
$ yarn android
# After app loaded, click the "PUSH" button and Android will throw the exception.
```

### Expected behavior

Should able to show next screen

### Actual behavior

Getting exception

## Package versions

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: 3.7.2

**Comment by WoLewicki** [comment]
@Kudo I added a PR concerning this behavior: #1148. This exception comes from using old tests, where `gestureEnabled: true` was available on `Android` with the addition of changing the `Fragment` transactions to being committed synchronously.

**Comment by Kudo** [comment]
thanks, @WoLewicki! the fix in your pr works for me. just to double confirm that android hardware back key support in ScreenStack will be deprecated and be a breaking change, right?

**Comment by WoLewicki** [comment]
Yeah, I believe it can be called breaking change if you use `react-native-screens` outside of `react-navigation`.

**Comment by Kudo** [comment]
@WoLewicki understand! thanks for your fix. 👏
