### ISSUE TITLE
iOS debug mode crash almost on every refresh

### ISSUE THREAD

**Issue by cristianoccazinsp** [software-mansion/react-native-screens#1211]
## Description
Refreshing the RN app causes `'NSInternalInconsistencyException', reason: 'This method must not be called before the JS thread is created`.

I've been seeing ever since day 1 enabling screens, but it has started to become a pain in neck to debug native code with XCode thanks to this. 

## Steps To Reproduce

1. Use screens
2. Refresh the app (reload?)
3. Repeat until a crash happens

The crash comes directly from RNScreens when trying to traverse scroll views. See stack trace below.

### Expected behavior
No crash

### Actual behavior
Crash

```
#3  0x000000010504d428 in -[RCTCxxBridge ensureOnJavaScriptThread:] at node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:367
#4  0x00000001050564b8 in -[RCTCxxBridge dispatchBlock:queue:] at node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:1209
#5  0x0000000105169ae8 in -[RCTEventDispatcher sendEvent:] at node_modules/react-native/React/CoreModules/RCTEventDispatcher.mm:170
#6  0x00000001050f194c in -[RCTScrollView sendScrollEventWithName:scrollView:userData:] at node_modules/react-native/React/Views/ScrollView/RCTScrollView.m:962
#7  0x00000001050ed948 in -[RCTScrollView scrollViewDidScroll:] at node_modules/react-native/React/Views/ScrollView/RCTScrollView.m:589
#8  0x00000001050ef068 in -[RCTScrollView scrollViewDidEndDecelerating:] at node_modules/react-native/React/Views/ScrollView/RCTScrollView.m:762
#9  0x0000000105008eb4 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:693
#10 0x0000000105008fd4 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
```

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.65.1        |
| @react-navigation/native               |  5.9.4       |
| @react-navigation/native-stack         |   5.14.9      |
| react-native-screens                   |  3.9.0       |
| react-native-safe-area-context         |  3.3.2       |
| react-native-gesture-handler           |    1.10.3     |
| react-native-reanimated                |  1.13.2       |
| expo                                   |     -    |

**Comment by WoLewicki** [comment]
@cristianoccazinsp can you check if applying https://github.com/software-mansion/react-native-screens/pull/1212 resolves the issue?

**Comment by cristianoccazinsp** [comment]
It does not, here's a full trace again.

```
#0	0x000000018153904c in __exceptionPreprocess ()
#1	0x0000000199badf54 in objc_exception_throw ()
#2	0x0000000182df2834 in -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] ()
#3	0x0000000102b792c4 in -[RCTCxxBridge ensureOnJavaScriptThread:] at node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:367
#4	0x0000000102b82354 in -[RCTCxxBridge dispatchBlock:queue:] at node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:1209
#5	0x0000000102c95988 in -[RCTEventDispatcher sendEvent:] at node_modules/react-native/React/CoreModules/RCTEventDispatcher.mm:170
#6	0x0000000102c1d7ec in -[RCTScrollView sendScrollEventWithName:scrollView:userData:] at node_modules/react-native/React/Views/ScrollView/RCTScrollView.m:962
#7	0x0000000102c197e8 in -[RCTScrollView scrollViewDidScroll:] at node_modules/react-native/React/Views/ScrollView/RCTScrollView.m:589
#8	0x0000000102c1af08 in -[RCTScrollView scrollViewDidEndDecelerating:] at node_modules/react-native/React/Views/ScrollView/RCTScrollView.m:762
#9	0x0000000102b34d50 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:693
#10	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#11	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#12	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#13	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#14	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#15	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#16	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#17	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#18	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#19	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#20	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#21	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#22	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#23	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#24	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#25	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#26	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#27	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#28	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#29	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#30	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#31	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#32	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#33	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#34	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#35	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#36	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#37	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#38	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#39	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#40	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#41	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#42	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#43	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#44	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#45	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#46	0x0000000102b34e70 in __35-[RNSScreen traverseForScrollView:]_block_invoke at node_modules/react-native-screens/ios/RNSScreen.m:696
#47	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#48	0x00000001814ec29c in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#49	0x0000000102b34de0 in -[RNSScreen traverseForScrollView:] at node_modules/react-native-screens/ios/RNSScreen.m:695
#50	0x0000000102b34c1c in -[RNSScreen viewDidDisappear:] at node_modules/react-native-screens/ios/RNSScreen.m:686
#51	0x0000000183af32bc in -[UIViewController _setViewAppearState:isAnimating:] ()
#52	0x00000001842e5bec in __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke_2 ()
#53	0x0000000183c15168 in __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke ()
#54	0x00000001814add68 in __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ ()
#55	0x0000000181534640 in -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] ()
#56	0x0000000183af368c in -[UIViewController _setViewAppearState:isAnimating:] ()
#57	0x0000000183bd2f88 in -[UIViewController __viewDidDisappear:] ()
#58	0x00000001842e61dc in __64-[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:]_block_invoke.1467 ()
#59	0x0000000183d8bcb8 in -[UIViewController _executeAfterAppearanceBlock] ()
#60	0x0000000183c71e5c in -[_UIAfterCACommitBlock run] ()
#61	0x0000000183b83fd4 in -[_UIAfterCACommitQueue flush] ()
#62	0x0000000183aaca44 in _runAfterCACommitDeferredBlocks ()
#63	0x0000000183aad15c in _cleanUpAfterCAFlushAndRunDeferredBlocks ()
#64	0x0000000183e892ec in _UIApplicationFlushCATransaction ()
#65	0x00000001841237d8 in _UIUpdateSequenceRun ()
#66	0x000000018479d008 in schedulerStepScheduledMainSection ()
#67	0x000000018479c5f8 in runloopSourceCallback ()
#68	0x000000018155b020 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#69	0x000000018156bce0 in __CFRunLoopDoSource0 ()
#70	0x00000001814a6054 in __CFRunLoopDoSources0 ()
#71	0x00000001814ab7f4 in __CFRunLoopRun ()
#72	0x00000001814bf3b8 in CFRunLoopRunSpecific ()
#73	0x000000019ce4f38c in GSEventRunModal ()
#74	0x0000000183e5f6a8 in -[UIApplication _run] ()
#75	0x0000000183bde7f4 in UIApplicationMain ()
#76	0x00000001029316b0 in main at ios/zinspector3/main.m:6
#77	0x0000000106401a24 in start ()
```
<img width="831" alt="Screen Shot 2021-11-17 at 09 19 12" src="https://user-images.githubusercontent.com/48869228/142199512-9393507d-aead-4f1b-97ec-293593bffbf6.png">

**Comment by cristianoccazinsp** [comment]
I think the patch above had a good insight of what's wrong, but the fix should be more like:

```
dispatch_async(dispatch_get_main_queue(), ^(void){
          [[(UIScrollView *)view delegate] scrollViewDidEndDecelerating:(id)view];
      });
```

I don't know the consequences of forcing this to run async in the main thread, but I believe this stops the crash.

**Comment by WoLewicki** [comment]
Can you check if https://github.com/software-mansion/react-native-screens/pull/1217 fixes the issue? And could you provide a quick repro of the problem?

**Comment by cristianoccazinsp** [comment]
Looks like #1217 fixes it, awesome!
