### ISSUE TITLE
[Android] Crash: could not find Fragment constructor

### ISSUE THREAD

**Issue by ammoradi** [software-mansion/react-native-screens#122]
these crashes happened on many devices based on firebase crashlytic report:
```
Caused by android.support.v4.app.k$b: Unable to instantiate fragment com.swmansion.rnscreens.b$a: could not find Fragment constructor
       at android.support.v4.app.Fragment.dump(Fragment.java:111)
       at android.support.v4.app.FragmentContainer.instantiate(FragmentContainer.java)
       at android.support.v4.app.FragmentState.instantiate(FragmentState.java:25)
       at android.support.v4.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:230)
       at android.support.v4.app.FragmentController.attachHost(FragmentController.java:4)
       at android.support.v4.app.FragmentActivity.onCreate + 42(FragmentActivity.java:42)
       at android.support.v7.app.AppCompatActivity.onCreate + 40(AppCompatActivity.java:40)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java)
       at com.bookapo.MainActivity.onCreate + 6(MainActivity.java:6)
       at android.app.Activity.performCreate + 7327(Activity.java:7327)
       at android.app.Activity.performCreate + 7318(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate + 1275(Instrumentation.java:1275)
       at android.app.ActivityThread.performLaunchActivity + 3095(ActivityThread.java:3095)
       at android.app.ActivityThread.handleLaunchActivity + 3258(ActivityThread.java:3258)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1955(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7073(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 964(ZygoteInit.java:964)
```

**Comment by frankyjuang** [comment]
same issue https://github.com/kmagiera/react-native-screens/issues/17?

**Comment by WoLewicki** [comment]
Looks like @frankyjuang is right and it is duplicate, I am closing it then. Feel free to comment if I am wrong.
