### ISSUE TITLE
Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault

### ISSUE THREAD

**Issue by Chasty** [software-mansion/react-native-screens#1409]
## Description
I have tried to run the example project and followed all the steps but got that issue after running `yarn ios`, any idea?

Cloned this repository then go into the FabricExample `yarn install` and `pod install` finally `yarn ios`.

### Screenshots

![Screen Shot 2022-04-13 at 21 57 23](https://user-images.githubusercontent.com/18494040/163305042-5ad23fa6-906b-4c6a-b5cf-03077a86b9dc.png)

## Steps To Reproduce

1. Follow the [Fabric Readme](https://github.com/software-mansion/react-native-screens/blob/main/README-Fabric.md)
2. Follow the [Fabric Example Readme](https://github.com/software-mansion/react-native-screens/blob/main/FabricExample/README.md)

### Expected behavior
Run the app correctly and see the example.

### Actual behavior

```
 BUNDLE  ./index.js 

error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/src/index.native.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project.
> 1 | import React from 'react';
  2 | import {
  3 |   Animated,
  4 |   Image,
    at ModuleResolver.resolveDependency (/Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/FabricExample/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/FabricExample/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/FabricExample/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/FabricExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/FabricExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/FabricExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/FabricExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/chasty/Documents/WillyWorkSpace/RN/Fabric/react-native-screens/FabricExample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 11)

```

## Reproduction

Example

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow
- [ ] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |       0.0.0-20220213-2008-7cece3423  |
| @react-navigation/native               |         |
| @react-navigation/native-stack         |         |
| react-native-screens                   |        link:../ |
| react-native-safe-area-context         |         |
| react-native-gesture-handler           |         |
| react-native-reanimated                |         |
| expo                                   |         |

**Comment by WoLewicki** [comment]
I have just run the `FabricExample` on `iOS` from the current `main` and it works correctly. Did you run `yarn` in the main folder of the repo first?

**Comment by WoLewicki** [comment]
Closing due to no response provided in 30 days. Feel free to comment to reopen.
