### ISSUE TITLE
crash when fabric is enabled.

### ISSUE THREAD

**Issue by pjc0247** [software-mansion/react-native-screens#1422]
## Description

App crashes after user touches the screen.

+ does not happen if fabric is disabled.
```
      reactRootView.setIsFabric(false);
```

```
2022-04-25 20:24:40.458 10036-10036/? D/ScrollView: initGoToTop
2022-04-25 20:24:40.465 10036-10036/? D/ScrollView: initGoToTop
2022-04-25 20:24:40.466 10036-10036/? I/ReactNative: [GESTURE HANDLER] Gesture handler is already enabled for a parent view
2022-04-25 20:24:40.467 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: caught exception, displaying mount state
    java.lang.IllegalStateException: addViewAt: failed to insert view [2048] into parent [202] at index 1
        at com.facebook.react.fabric.mounting.SurfaceMountingManager.addViewAt(SurfaceMountingManager.java:344)
        at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:153)
        at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:352)
        at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:275)
        at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:120)
        at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1163)
        at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
        at android.view.Choreographer.doFrame(Choreographer.java:792)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalStateException: Parent Screen does not have its Fragment attached
        at com.swmansion.rnscreens.ScreenContainer.setupFragmentManager(ScreenContainer.kt:150)
        at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.kt:199)
        at android.view.View.dispatchAttachedToWindow(View.java:21976)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4293)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:6127)
        at android.view.ViewGroup.addView(ViewGroup.java:5903)
        at android.view.ViewGroup.addView(ViewGroup.java:5843)
        at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:37)
        at com.facebook.react.fabric.mounting.SurfaceMountingManager.addViewAt(SurfaceMountingManager.java:341)
        at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:153) 
        at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:352) 
        at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:275) 
        at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:120) 
        at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1163) 
        at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:866) 
        at android.view.Choreographer.doFrame(Choreographer.java:792) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8663) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: IntBufferBatchMountItem [surface:1]:
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: REMOVE [192]->[200] @5
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: REMOVE [54]->[200] @4
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: REMOVE [40]->[200] @3
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: REMOVE [56]->[200] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: REMOVE [194]->[200] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [194]->[198] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [56]->[198] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [40]->[198] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [54]->[198] @3
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [192]->[198] @4
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1636] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1634] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1632] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1632]->[1634] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1634]->[1636] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1636]->[1638] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1638]->[1642] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1646]->[1648] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1642]->[1650] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1648]->[1650] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1656] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1654] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1652] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1652]->[1654] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1654]->[1656] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1660]->[1662] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1656]->[1662] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1658]->[1662] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1662]->[1664] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1668]->[1670] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1674]->[1676] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1680]->[1682] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1676]->[1686] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1682]->[1686] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1686]->[1688] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1692]->[1694] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1698]->[1700] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1694]->[1704] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1700]->[1704] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1704]->[1706] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1688]->[1708] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1706]->[1708] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1708]->[1710] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1710]->[1712] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1670]->[1714] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1712]->[1714] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1730] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1728] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1716] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1718] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1720] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1722] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1724] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1726] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1716]->[1728] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1718]->[1728] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1720]->[1728] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1722]->[1728] @3
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1724]->[1728] @4
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1726]->[1728] @5
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1728]->[1730] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1730]->[1740] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1736]->[1740] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1738]->[1740] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1754] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1752] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1742] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1744] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1746] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1748] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1750] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1742]->[1752] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1744]->[1752] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1746]->[1752] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1748]->[1752] @3
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1750]->[1752] @4
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1752]->[1754] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1754]->[1764] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1760]->[1764] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1762]->[1764] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1772] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1770] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1766] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1768] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1766]->[1770] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1768]->[1770] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1770]->[1772] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1772]->[1782] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1778]->[1782] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1780]->[1782] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1790] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1788] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1784] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1786] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1784]->[1788] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1786]->[1788] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1788]->[1790] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1790]->[1800] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1796]->[1800] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1798]->[1800] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1820] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1818] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1802] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1804] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1806] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1808] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1810] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1812] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1814] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1816] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1802]->[1818] @0
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1804]->[1818] @1
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1806]->[1818] @2
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1808]->[1818] @3
2022-04-25 20:24:40.495 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1810]->[1818] @4
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1812]->[1818] @5
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1814]->[1818] @6
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1816]->[1818] @7
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1818]->[1820] @0
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1820]->[1830] @0
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1826]->[1830] @1
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: INSERT [1828]->[1830] @2
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1846] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1844] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1832] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1834] - layoutable:1 - UnimplementedNativeView
2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1836] - layoutable:1 - UnimplementedNativeView


/* ... */

2022-04-25 20:24:40.496 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: CREATE [1838] - 

2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1692]: x:0 y:0 w:540 h:53 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1762]: x:37 y:142 w:1006 h:2 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1806]: x:0 y:0 w:84 h:0 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1820]: x:37 y:38 w:84 h:84 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1826]: x:157 y:45 w:259 h:53 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1828]: x:37 y:142 w:1006 h:3 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1864]: x:0 y:0 w:13 h:3 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1868]: x:0 y:3 w:84 h:0 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1858]: x:0 y:0 w:84 h:0 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1888]: x:37 y:142 w:1006 h:2 displayType:1
2022-04-25 20:24:40.499 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1904]: x:0 y:0 w:84 h:0 displayType:1
2022-04-25 20:24:40.500 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1944]: x:0 y:0 w:84 h:0 displayType:1
2022-04-25 20:24:40.500 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1946]: x:0 y:0 w:84 h:0 displayType:1
2022-04-25 20:24:40.500 10036-10036/? E/unknown:MountItemDispatcher: dispatchMountItems: mountItem: UPDATE LAYOUT [1980]: x:157 y:45 w:185 h:53 displayType:1

```

## Steps To Reproduce

1.

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [ ] Bare workflow

## Package versions

```
"react-native": "0.68.1",
"react-native-gesture-handler": "^2.4.1",
"react-native-reanimated": "2.8.0",
"react-native-safe-area-context": "^4.2.4",
"react-native-screens": "^3.13.1",
```

**Comment by WoLewicki** [comment]
I think this issue is quite similar to https://github.com/software-mansion/react-native-screens/issues/1405 since in the stack trace I can see `ScreenContainer`, which does not yet support Fabric. We are in process of migrating it so it should be available soon 💪

**Comment by MLawlz** [comment]
Just wanted to post here that I'm running into the same problem with version 3.15.0. It looks like in the prior release notes that ScreenContainer was migrated to Fabric, so shouldn't this be addressed?

**Comment by pjc0247** [comment]
Sorry, but i can't test this since i've deleted migration(fabric) branch.

In fact, I tried one more time with the new 0.69.1 version, but it took a lot of time to set up the development environment and eventually failed.

**Comment by pierroo** [comment]
> Just wanted to post here that I'm running into the same problem with version 3.15.0. It looks like the prior release notes mention that ScreenContainer was migrated to Fabric, so shouldn't this be addressed?

I am on 3.15.0 (react native 0.66.0); getting the same error; which is weird since I never got it before.
tried all kind of delete node_modules / clearing cache / restarting the computer etc, without luck.

Did you manage to find a solution? :)

**Comment by kkafar** [comment]
@pierroo Can you confirm for me that you're using React Native 0.66.0 indeed => not using Fabric => this issue is not Fabric related? 

Could anyone provide us with reproduction? I did not succeed in reproducing this.

**Comment by markholland** [comment]
We're seeing this after enabling new architecture on Android with `3.17.0` on React Native `0.69.6` 
Example project: https://github.com/catenda/pdftron-example-react-native/tree/d53a502bf7d603a53fe32d345962908c2d94d8a5

![screencap-2022-10-11T132656 600Z copy](https://user-images.githubusercontent.com/1764217/195103808-4b423fe3-ede3-41fa-9787-9d3a0facabfd.png)

**Comment by hosseinmd** [comment]
Exact same issue happened with v3.34.0 on react-native v0.75 and new arch enabled

**Comment by pierroo** [comment]
> Exact same issue happened with v3.34.0 on react-native v0.75 and new arch enabled

did you find a solution to this since?
I'm on RN 0.79.3, new arch enabled, and randomly facing it when navigating.

**Comment by kkafar** [comment]
@pierroo can you provide a reproduction to this problem?

**Comment by pierroo** [comment]
> [@pierroo](https://github.com/pierroo) can you provide a reproduction to this problem?

super hard to provide, since it happens very randomly.
I also think it MAY be related to this reanimated issue:
https://github.com/software-mansion/react-native-screens/issues/1422#issuecomment-2976571100

although I don't know which one is responsible truly since react-native-screens depend on reanimated.

perhaps those screenshot would help from crashlytics:

![Image](https://github.com/user-attachments/assets/3d6f3354-ca95-4759-8eaf-3df984363de8)

![Image](https://github.com/user-attachments/assets/9040c818-72db-40bf-bbef-54d983acf57c)
