### ISSUE TITLE
Crash on startup on android

### ISSUE THREAD

**Issue by arcollector** [software-mansion/react-native-screens#1580]
### Description

Hello, I am using latest version 3.17.0 and I getting this error

```
    java.lang.NoSuchFieldError: No static field rns_no_animation_20 of type I in class Lcom/swmansion/rnscreens/R$anim; or its superclasses (declaration of 'com.swmansion.rnscreens.R$anim' appears in /data/app/~~uCOWk_NFFQHVyezoxKR6aA==/com.seguro.app-Gw5hyuLxxPrZIAIpc5-G6Q==/base.apk!classes18.dex)
        at com.swmansion.rnscreens.ScreenStack.onUpdate(ScreenStack.kt:146)
        at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.kt:328)
        at com.swmansion.rnscreens.ScreenContainer.performUpdatesNow(ScreenContainer.kt:320)
        at com.swmansion.rnscreens.ScreenContainer.setFragmentManager(ScreenContainer.kt:135)
        at com.swmansion.rnscreens.ScreenContainer.setupFragmentManager(ScreenContainer.kt:188)
        at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.kt:228)
        at android.view.View.dispatchAttachedToWindow(View.java:22010)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4291)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
        at android.view.ViewGroup.addView(ViewGroup.java:5884)
        at android.view.ViewGroup.addView(ViewGroup.java:5824)
        at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:37)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
        at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:306)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:740)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

My package.json is the following
```
 "dependencies": {
   
    "@react-navigation/drawer": "6.4.4",
    "@react-navigation/material-top-tabs": "6.2.3",
    "@react-navigation/native": "6.0.12",
    "@react-navigation/native-stack": "6.8.0",
  
    "react": "17.0.2",
  
    "react-native": "0.68.2",
   
    "react-native-gesture-handler": "2.6.0",
 
    "react-native-pager-view": "5.4.25",
 
    "react-native-reanimated": "2.10.0",
    "react-native-safe-area-context": "4.3.3",
    "react-native-screens": "3.17.0",
    
    "react-native-tab-view": "3.1.1",

  },
```

### Steps to reproduce

I dont have any stetps to reproduce, this error appears today from nowhere I didn't install any deps

### Snack or a link to a repository

https://github.com/arcollector/rnscreen-bug

### Screens version

3.17.0

### React Native version

0.68.2

### Platforms

Android

### Workflow

React Native (without Expo)

### Acknowledgements

Yes

**Comment by arcollector** [comment]
I solved!!! I need to remove these damn folders

`rm -rf android/build android/app/build`
