### ISSUE TITLE
Could not find generated setter for class com.swmansion.rnscreens.ScreensShadowNode

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [software-mansion/react-native-screens#1648]
### Description

2022-11-29 22:41:18.670 28399-28399/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 28399
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/MenuHost;
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3532)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.MenuHost" on path: DexPathList[[zip file "/data/app/~~PbJ2yKl4vEnmo6Wh8nx43A==/com.myapp-3DZxYnzQfxScDp-BjwsKCw==/base.apk"],nativeLibraryDirectories=[/data/app/~~PbJ2yKl4vEnmo6Wh8nx43A==/com.myapp-3DZxYnzQfxScDp-BjwsKCw==/lib/arm64, /data/app/~~PbJ2yKl4vEnmo6Wh8nx43A==/com.myapp-3DZxYnzQfxScDp-BjwsKCw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1273) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3532) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 

    "react-native": "0.70.6",
    "react": "18.1.0",

 "react-native-screens": "^3.18.2",

### Steps to reproduce
Updating app from react-native :0.67.4 to 0.70.2
Open app if react-naviagtion is added, it crashes.

### Screens version

3.18.2

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

pixel_2

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi @CHANDRAMOHANnegi,

I've got few remarks.

1. In the stack trace you provided there is actually nothing concerning `react-native-screens`. I guess some substantial parts are missing then, please provide them. 
2. Please provide a reproduction, as the bot suggests.
3. My first impression is that migration process from 0.67.x to 0.70.x could be done wrong. Please note, that there are multiple steps to be done during such migration. I recommend using [this tool - React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.67.4&to=0.70.6) - it shows differences in react native templates in respective React Native versions and can be used as a instruction of what needs to be changed in your application to work on targeted React Native version.

However these are only my first thoughts, based on error message from PR title, which indicates that codegen / linking is set up incorrect.

**Comment by CHANDRAMOHANnegi** [comment]
commented below code  and fixed

configurations.all {
  resolutionStrategy {
    force 'androidx.core:core-ktx:1.6.0'
    force 'androidx.core:core:1.6.0'
  }
}

was issue with androidx and not with react-native-screens
