### ISSUE TITLE
[Android Crash] App crashes when already granted Location permission is revoked

### ISSUE THREAD

**Issue by latobibor** [software-mansion/react-native-screens#1764]
### Description

The app crashes on Android (both on physical device and emulator).

(I'm aware of the link in the stack trace about fragments).

```
17:30:49.622  E  FATAL EXCEPTION: main
                 Process: com.acasusdata.gen, PID: 9867
                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.acasusdata.gen/com.acasusdata.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7839)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                 Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
                 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
                 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
                 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
                 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
                 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
                 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
                 	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
                 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
                 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
                 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
                 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
                 	at android.app.Activity.performCreate(Activity.java:8051)
                 	at android.app.Activity.performCreate(Activity.java:8031)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loopOnce(Looper.java:201) 
                 	at android.os.Looper.loop(Looper.java:288) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
                 Caused by: java.lang.reflect.InvocationTargetException
                 	at java.lang.reflect.Constructor.newInstance0(Native Method)
                 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
                 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
                 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
                 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
                 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
                 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
                 	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
                 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
                 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322) 
                 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
                 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
                 	at android.app.Activity.performCreate(Activity.java:8051) 
                 	at android.app.Activity.performCreate(Activity.java:8031) 
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608) 
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loopOnce(Looper.java:201) 
                 	at android.os.Looper.loop(Looper.java:288) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
                 Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
                 	at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:54)
                 	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
                 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613) 
                 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
                 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
                 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
                 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
                 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
                 	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
                 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
                 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322) 
                 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
                 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
                 	at android.app.Activity.performCreate(Activity.java:8051) 
                 	at android.app.Activity.performCreate(Activity.java:8031) 
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608) 
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loopOnce(Looper.java:201) 
                 	at android.os.Looper.loop(Looper.java:288) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

(Sorry the github link is for another issue, I did not have time to download a new template, add minimal UI, add permission, etc.)

### Steps to reproduce

1. Open application
2. Give Location permission
3. Open Settings
4. Take away Location permission
5. Navigate back

**Expected Result**
The application is able to continue working normally.

**Actual result**
The application just crashes.

### Screens version

3.20.0

### React Native version

0.69.9

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

None

### Acknowledgements

Yes

**Comment by latobibor** [comment]
The "fix" avoids crash but in reality does not really improve anything. The only thing this ticket has a deterministic way to crash the app. So I close the issue.
