### ISSUE TITLE
Facing crash issue when putting app in background. 

### ISSUE THREAD

**Issue by pyshagrwl** [software-mansion/react-native-screens#1774]
### Description

**Environment:** Please check below version of lib we are using
- React Native (Android) Version : 0.68.7
- "@react-navigation/native": "6.0.16",
- "@react-navigation/stack": "6.3.7",
- "react-native-screens": "3.20.0",
-  Hermes is enabled for our project 

When we are putting our application in background and when coming back to application we are facing crash issue. Please check below crash logs for the same. 

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app.uat/com.my.app.home.LandingActivity}: androidx.fragment.app.Fragment$l: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

Caused by androidx.fragment.app.Fragment$l: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:681)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:507)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
       at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2505)
       at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1989)
       at androidx.fragment.app.Fragment.onCreate(Fragment.java:1965)
       at com.facebook.react.ReactFragment.onCreate(ReactFragment.java:57)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
       at com.videoready.libraryfragment.ui.BaseActivity.onCreate(BaseActivity.java:33)
       at com.my.app.TSBaseActivity.onCreate(TSBaseActivity.java:115)
       at com.my.app.nav.NavBaseActivity.onCreate(NavBaseActivity.kt:353)
       at com.my.app.home.LandingActivity.onCreate(LandingActivity.java:250)
       at android.app.Activity.performCreate(Activity.java:8129)
       at android.app.Activity.performCreate(Activity.java:8109)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:663)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:507)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
       at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2505)
       at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1989)
       at androidx.fragment.app.Fragment.onCreate(Fragment.java:1965)
       at com.facebook.react.ReactFragment.onCreate(ReactFragment.java:57)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
       at com.videoready.libraryfragment.ui.BaseActivity.onCreate(BaseActivity.java:33)
       at com.my.app.TSBaseActivity.onCreate(TSBaseActivity.java:115)
       at com.my.app.nav.NavBaseActivity.onCreate(NavBaseActivity.kt:353)
       at com.my.app.home.LandingActivity.onCreate(LandingActivity.java:250)
       at android.app.Activity.performCreate(Activity.java:8129)
       at android.app.Activity.performCreate(Activity.java:8109)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

Caused by java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
       at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:54)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:663)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:507)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:81)
       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
       at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2505)
       at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1989)
       at androidx.fragment.app.Fragment.onCreate(Fragment.java:1965)
       at com.facebook.react.ReactFragment.onCreate(ReactFragment.java:57)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
       at com.videoready.libraryfragment.ui.BaseActivity.onCreate(BaseActivity.java:33)
       at com.my.app.TSBaseActivity.onCreate(TSBaseActivity.java:115)
       at com.my.app.nav.NavBaseActivity.onCreate(NavBaseActivity.kt:353)
       at com.my.app.home.LandingActivity.onCreate(LandingActivity.java:250)
       at android.app.Activity.performCreate(Activity.java:8129)
       at android.app.Activity.performCreate(Activity.java:8109)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

Though we found solution in crash logs itself https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067. But we are loading ReactFragment instead of ReactActivity. 

```
  Fragment reactNativeFragment = new ReactFragment.Builder()
      .setComponentName(Constants.DEFAULT_APP_NAME)
      .setLaunchOptions(getLaunchOptions())
      .build();

  getParentFragmentManager()
       .beginTransaction()
       .add(R.id.reactNativeFragment, reactNativeFragment)
       .commitAllowingStateLoss();
```
I gone through the already issue raised but did not get any solution for the fragment implementation. 

@kmagiera: Need your help here to resolve the issue at earliest. 

### Steps to reproduce

1. After launching application if we are putting application in background.
2. opening back after some time getting crash issue. 

### Snack or a link to a repository

https://snack.expo.dev/@pysh.agrwl.10/app-bg-crash-issue

### Screens version

3.20.0

### React Native version

0.68.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

ZenFone Max Pro M1 (ZB602KL) (WW) / Max Pro M1 (ZB601KL), OnePlus Nord CE 5G, OPPO-CPH2213, Redmi Note 9 Pro Max, Redmi Note 10S,  (IN), Motorolla

### Acknowledgements

Yes

**Comment by jakecurreri** [comment]
For my prod app, users just recently started reporting this issue. Not sure if an OS update for Android is causing the uptick in reports. Since realized we never overrode the `onCreate` method in `MainActivity.java`.

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        //react-native-screens override
        super.onCreate(null);
        ....
    }
```

**Comment by pyshagrwl** [comment]
@jakecurreri We dont have any activity which is extending `ReactActivity`. We have Single Activity architecture in our project and launching react through fragment as mentioned in above code.

**Comment by pyshagrwl** [comment]
@kmagiera Need your help here to resolve this issue, can you please update us on this issue?

**Comment by kkafar** [comment]
Hey, thank for reporting. 

What I would need from your side to have a chance of successfully debugging this issue is a valid reproduction. Can you provide me with [setup where I can reliably reproduce the issue](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Abbondanzo** [comment]
## What's the cause (and how can we repro?)

Wanted to follow up on this issue since we've also been running into it. In the shortest possible explanation, this can happen to hybrid apps who instantiate React Native within a Fragment and not an Activity. The stereotypical solution of resetting the Activity's saved instance state to `null` _is_ a workaround in cases where you have a single-Activity architecture, but it's not a sustainable approach in hybrid applications.

This issue can happen if the backing Activity housing the React Native Fragment is ever destroyed. To quickly reproduce this, you can toggle "Don't keep activities" on in Developer Options and launch a native Activity from another activity with a React Native fragment inside it (assuming you don't use the aforementioned workaround with saved instance states). For obvious reasons, this type of setup isn't easily shared via Expo snack so I've whipped up a quick demo repository containing the basic setup [here](https://github.com/Abbondanzo/ScreensDemo).

### A deep dive

What's happening is that the Fragment instance housing React Native is re-instantiating its child fragments from state. The state provided to a Fragment's `onCreate` method is similar but not the same as an Activity's persisted state: an Activity persists its `FragmentManagerState` in the singular bundle passed to `onCreate` (under the `android:fragments` key) while a Fragment's state is persisted a bit differently.

- In view pagers, a Fragment persists its `FragmentManagerState` internally in its `mSavedFragmentState` bundle (under the `childFragmentManager` key). The pager calls the Fragment's `setInitialSavedState` function to perform this override and the Fragment later restores its child Fragments with this state.

- In a `FragmentActivity`, the Activity implements the `SavedStateRegistryOwner` interface, giving the Activity's FragmentManager independent access into a registry containing this state. In fact, _many_ classes and even the `Fragment` class itself implements this interface and contains similar logic for providing state outside the methods afforded to us for override. It's here where our React Native Fragment is instantiated, regardless of whether or not the Fragment has been told to be retained. As soon as the Fragment is instantiated, the FragmentManager sets its `mSavedFragmentState` property.

In both of these code paths, the `mSavedFragmentState` property is set before we can even hijack the bundle and tell it not to instantiate any Screen Fragments; it gets set before `onCreate` is called. But it's in `onCreate` that the child `FragmentManagerState` is restored (via `restoreSaveStateInternal`) and each of the children receive a `CREATED` state change (via `dispatchCreate`).

## How do we fix this?

Let's look at possible options. We can't use the parent FragmentManager's `saveFragmentInstanceState`, it only invokes the Fragment's `onSaveInstanceState` and builds a separate bundle for future instantiations and is only used for view operations. Moreover, the actual fragment hierarchy is saved by the parent Activity. We can't call `setInitialSavedState` on the Fragment, it already has a FragmentManager set and raises an exception. We _could_ use reflection to grab the `mSavedFragmentState` Bundle and completely annihilate the `childFragmentManager` key, but reflection is always dangerous outside of a developer environment.

What if we removed all references to screen Fragments before beginning the process of destroying the React Native Fragment? If we lean into the Fragment's lifecycle methods like `onPause` and `onStop`, we can combat this. Unfortunately, `onPause` is called with the expectation that the Activity is going to resume momentarily. It's not a reliable indicator that the Activity is going to stop, so we can't use it. And `onStop` doesn't necessarily mean the Activity has been destroyed, it just means that it has been completely covered by something else. We can't perform operations on the `childFragmentManager` in the `onDestroy` method; by this point, the FragmentManager has been marked as stopped and had all its fragments removed. We can't perform any modifications to the FragmentManager once `onSaveInstanceState` has been called.

If it weren't for the exception thrown in ScreenFragment and ScreenStackFragment constructors, we could store old Fragments and safely remove our them before they ever get mounted. A simple transaction during creation of the parent Fragment:

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
  super.onCreate(savedInstanceState)
  val transaction = childFragmentManager.beginTransaction()
  val oldFragments = myViewModel.getOldFragments()
  for (fragment in oldFragments) {
    transaction.remove(fragment)
  }
  transaction.commitNowAllowingStateLoss()
}
```

Or we could extend this concept to the ScreenFragments themselves: they can remove themselves upon creation if the `screen` parameter was made nullable. With the smallest amount of changes, you could get away with checking on the if `screen` has been initialized. If patch-package is available to you, you can set `onCreate` and `onDestroy` in your `ScreenFragment.kt` file with the following:

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
  super.onCreate(savedInstanceState)
  if (!this::screen.isInitialized) {
    parentFragmentManager.beginTransaction().remove(fragment).commit()
  }
}

override fun onDestroy() {
  super.onDestroy()
  if (!this::screen.isInitialized) {
    return
  }
  // ...rest of the implementation, don't forget to copy this!!!
}
```

However, these are both hacks! I haven't found a safe workaround other than completely disabling `react-native-screens` when embedding React Native anywhere. It's safe to use in the context of an Activity that you control, but not elsewhere in a hybrid application.

## An aside

Throwing an exception in the class constructor for `ScreenFragment` and `ScreenStackFragment` is antithetical to the design of Android Fragments. It addresses the symptoms of state loss between the native lifecycle and JavaScript runtime by prescribing a solution but doesn't work neatly within the Android lifecycle. State retention in Views and Fragments is strongly discouraged (hence ViewModels) but I do think it would be entirely within reason to allow `ScreenFragment` instances to destroy themselves. If any Fragment should ever be instantiated without the `screen` constructor argument, then it should safely perform that destruction, detaching itself from any parent FragmentManager. We can reasonably assume that the React Native Fragment has already instantiated a new `ScreenFragment` and is rendering that.
