### ISSUE TITLE
MainActivity getting destroyed intermittently / App is crashing while opening camera multiple times.

### ISSUE THREAD

**Issue by manishadp** [software-mansion/react-native-screens#1816]
### Description

**For react-native screens, we tried with multiple versions, from 3.17.0 to 3.22.0, but in vain.**

**In super.onCreate, when we pass savedInstanceState as null (super.onCreate(null)) and open the camera multiple times ( Approximately 10-15 times), MainActivity is getting re-created and the app is re-launching.**

**If we pass super.onCreate(savedInstanceState)  and do the same steps again then i'm getting below issue.**

androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3834)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8296)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                                                                                    Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
                                                                                                    	at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
                                                                                                    	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
                                                                                                    	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
                                                                                                    	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
                                                                                                    	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
                                                                                                    	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
                                                                                                    	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
                                                                                                    	at com.adp.time.kiosk.MainActivity.onCreate(MainActivity.java:70)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8523)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8487)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211) 
                                                                                                    	at android.os.Looper.loop(Looper.java:300) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8296) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
                                                                                                    	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
                                                                                                    	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
                                                                                                    	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
                                                                                                    	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
                                                                                                    	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
                                                                                                    	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
                                                                                                    	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362) 
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
                                                                                                    	at com.adp.time.kiosk.MainActivity.onCreate(MainActivity.java:70) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8523) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8487) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211) 
                                                                                                    	at android.os.Looper.loop(Looper.java:300) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8296) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 
                                                                                                    Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.

### Steps to reproduce

1. Open camera.
2. Close camera.
3. Do the above steps repeatedly (opening and closing the camera).

### Snack or a link to a repository

https://stackoverflow.com/questions/57709742/unable-to-instantiate-fragment-com-swmansion-rnscreens-screen

### Screens version

3.22.0

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

None

### Architecture

None

### Build type

None

### Device

Real device

### Device model

All devices

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @manishadp, thanks for the feedback! Could you provide us a link to the repository with code where the problem occurs, so we could reproduce the problem with provided steps?

**Comment by manishadp** [comment]
Unfortunately we work for an organisation and we are not allowed to share the code. Just adding some more info - This is basically happening when we are trying to open and close the camera repeatedly multiple times.
