### ISSUE TITLE
Android occasionally crashes when opening applications安卓打开应用偶尔闪退

### ISSUE THREAD

**Issue by show110695** [software-mansion/react-native-screens#2012]
### Description

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tiltandco.pocketguide/com.pocketbook.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3987)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4140)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2585)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:224)
 at android.os.Looper.loop(Looper.java:318)
 at android.app.ActivityThread.main(ActivityThread.java:8744)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
 at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
 at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
 at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
 at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
 at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
 at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
 at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
 at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
 at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:352)
 at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
 at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
 at android.app.Activity.performCreate(Activity.java:8891)
 at android.app.Activity.performCreate(Activity.java:8856)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3969)
 ... 12 more
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
 at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
 ... 26 more
Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
 at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:57)
 at com.swmansion.rnscreens.ScreenStackFragment.<init>(ScreenStackFragment.kt:38)
 ... 29 more

### Steps to reproduce

"dependencies": {
    "@eva-design/eva": "^2.2.0",
    "@native-html/table-plugin": "^5.3.1",
    "@react-native-community/geolocation": "^3.1.0",
    "@react-native-community/netinfo": "^11.2.0",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.14",
    "@rneui/base": "^4.0.0-rc.8",
    "@rneui/themed": "^4.0.0-rc.8",
    "@ui-kitten/components": "^5.3.1",
    "axios": "^1.6.2",
    "dayjs": "^1.11.10",
    "react": "18.2.0",
    "react-native": "0.72.9",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.13.2",
    "react-native-get-random-values": "^1.10.0",
    "react-native-reanimated": "^3.6.1",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "3.29.0",
    "react-native-svg": "^13.14.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.0.2",
    "react-native-webview": "^13.6.2",
    "realm": "^12.3.1",
    "rn-fetch-blob": "0.13.0-beta.2",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  }

### Snack or a link to a repository

https://play.google.com/store/apps/details?id=com.tiltandco.pocketguide

### Screens version

3.29.0

### React Native version

0.72.9

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by yedi97** [comment]
same

**Comment by tboba** [comment]
Hi @show110695, thank you for submitting this issue.
As described in the error you've put in the description, this problem is mostly related to the issue #17. Have you tried to override `onCreate` in your app activity, as mentioned here: https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 ?

**Comment by malikArslan112** [comment]
I have added 
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);
}
```
these lines in` MainActivity.java`.
But still getting this issue
**[native] screen fragments should never be restored. follow instructions from https://github.com/soft**

**Comment by malikArslan112** [comment]
> @malikArslan112 do you have any indications under what circumstances does this crash happen?

@kkafar This crash occurs mostly when Application state is changed from Background to Foreground

**Comment by mobinni** [comment]
@kkafar I see a similar thing occur, here's an excerpt from a stack trace.
RN version 0.77, Screens 4.5.0

```
android.view.ViewGroup in getAndVerifyPreorderedIndex at line 2137
android.view.ViewGroup in dispatchDraw at line 4558
android.view.View in draw at line 25197
android.view.View in updateDisplayListIfDirty at line 24053
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
com.facebook.react.views.view.ReactViewGroup in fsSuperDrawChild_edb44d086c450535af83dcbd575eea11 at line 8
com.facebook.react.views.view.ReactViewGroup in drawChild at line 902
android.view.ViewGroup in dispatchDraw at line 4587
com.facebook.react.views.view.ReactViewGroup in fsSuperDispatchDraw_edb44d086c450535af83dcbd575eea11 at line 7
com.facebook.react.views.view.ReactViewGroup in dispatchDraw at line 874
android.view.View in draw at line 25197
com.facebook.react.views.view.ReactViewGroup in fsSuperDraw_edb44d086c450535af83dcbd575eea11 at line 7
com.facebook.react.views.view.ReactViewGroup in draw at line 865
android.view.View in updateDisplayListIfDirty at line 24053
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
android.view.ViewGroup in dispatchDraw at line 4587
android.view.View in updateDisplayListIfDirty at line 24039
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
androidx.coordinatorlayout.widget.CoordinatorLayout in fsSuperDrawChild_4774dcc000161de84c13d383cdfdce85 at line 8
androidx.coordinatorlayout.widget.CoordinatorLayout in drawChild at line 1312
android.view.ViewGroup in dispatchDraw at line 4562
androidx.coordinatorlayout.widget.CoordinatorLayout in fsSuperDispatchDraw_4774dcc000161de84c13d383cdfdce85 at line 7
androidx.coordinatorlayout.widget.CoordinatorLayout in dispatchDraw
android.view.View in updateDisplayListIfDirty at line 24039
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
com.swmansion.rnscreens.ScreenStack in fsSuperDrawChild_54f485c8347fe5287e3da5fdd01b8593 at line 8
com.swmansion.rnscreens.ScreenStack in performDraw at line 406
com.swmansion.rnscreens.ScreenStack in access$performDraw at line 16
com.swmansion.rnscreens.ScreenStack$DrawingOp in draw at line 419
com.swmansion.rnscreens.ScreenStack in drawAndRelease at line 369
com.swmansion.rnscreens.ScreenStack in dispatchDraw at line 385
android.view.View in updateDisplayListIfDirty at line 24039
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
android.view.ViewGroup in dispatchDraw at line 4587
android.view.View in updateDisplayListIfDirty at line 24039
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
android.view.ViewGroup in dispatchDraw at line 4562
android.view.View in updateDisplayListIfDirty at line 24039
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
android.view.ViewGroup in dispatchDraw at line 4562
android.view.View in updateDisplayListIfDirty at line 24039
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
com.facebook.react.views.view.ReactViewGroup in fsSuperDrawChild_edb44d086c450535af83dcbd575eea11 at line 8
com.facebook.react.views.view.ReactViewGroup in drawChild at line 902
android.view.ViewGroup in dispatchDraw at line 4587
com.facebook.react.views.view.ReactViewGroup in fsSuperDispatchDraw_edb44d086c450535af83dcbd575eea11 at line 7
com.facebook.react.views.view.ReactViewGroup in dispatchDraw at line 874
android.view.View in draw at line 25197
com.facebook.react.views.view.ReactViewGroup in fsSuperDraw_edb44d086c450535af83dcbd575eea11 at line 7
com.facebook.react.views.view.ReactViewGroup in draw at line 865
android.view.View in updateDisplayListIfDirty at line 24053
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
android.view.ViewGroup in dispatchDraw at line 4587
android.view.View in updateDisplayListIfDirty at line 24039
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
androidx.coordinatorlayout.widget.CoordinatorLayout in fsSuperDrawChild_4774dcc000161de84c13d383cdfdce85 at line 8
androidx.coordinatorlayout.widget.CoordinatorLayout in drawChild at line 1312
android.view.ViewGroup in dispatchDraw at line 4562
androidx.coordinatorlayout.widget.CoordinatorLayout in fsSuperDispatchDraw_4774dcc000161de84c13d383cdfdce85 at line 7
androidx.coordinatorlayout.widget.CoordinatorLayout in dispatchDraw
android.view.View in updateDisplayListIfDirty at line 24039
android.view.View in draw at line 24924
android.view.ViewGroup in drawChild at line 4804
com.swmansion.rnscreens.ScreenStack in fsSuperDrawChild_54f485c8347fe5287e3da5fdd01b8593 at line 8
com.swmansion.rnscreens.ScreenStack in performDraw at line 406
com.swmansion.rnscreens.ScreenStack in access$performDraw at line 16
com.swmansion.rnscreens.ScreenStack$DrawingOp in draw at line 419
com.swmansion.rnscreens.ScreenStack in drawAndRelease at line 369
com.swmansion.rnscreens.ScreenStack in dispatchDraw at line 385
```
