### ISSUE TITLE
Multiple transitions between screens causes app to crash

### ISSUE THREAD

**Issue by marklawlor** [software-mansion/react-native-screens#2578]
### Description

Repeated navigation between 2 screens using React Navigation's Native Stack with a `getId()` prop causes the app to "crash". I use the term crash loosely as the behaviour is different per platform but both result in the app becoming unusable.

## iOS

`react-native` elements that use Pressibility become stuck in their "onPress" state, preventing them from receiving further onPress events. The issue does not occur with non-Pressibility elements such as `<TouchableOpacity />`.

You can observe this behaviour with the reproduction snack by repeatedly moving between the two screens using the Forwards/Backwards `<Text />` items. After 3 transitions, the `<Text />` items are no longer pressable and will be rendered with their `onPress` highlighting.

## Android

After 3 transitions, the native stack header will disappear. After 4 transitions, the native stack will no longer render any visible context.

Expo Router issue: https://github.com/expo/expo/issues/33658
React Navigation issue: https://github.com/react-navigation/react-navigation/issues/12346

### Steps to reproduce

1. Open Snack
2. Click "forwards" / "backwards" 3-5 times

### Snack or a link to a repository

https://snack.expo.dev/@mwlawlor/react-navigation-native-stack-stuck

### Screens version

3.3.0

### React Native version

0.76.3

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Mokhtar25** [comment]
Facing the same issue right now

**Comment by mlukasik-dev** [comment]
My app with expo-router is affected by this problem.

**Comment by kashmiry** [comment]
I am also facing this issue on **Android**. 
On iOS everything works fine.

When I navigate back to the same screen with the same `getId`, I observe the described behavior.
However, in my actual app, where I have a lot of integrations, this issue results in a crash with the following error:

```
The specified child already has a parent. You must call removeView() on the child's parent first
```

The temporary fix working for me now on Android is conditionally using `navigateDeprecated` if Platform is Android:
`navigation.navigateDeprecated(name, params);`

| Package                          | Version  |
|----------------------------------|----------|
| react                            | 18.2.0   |
| react-native                     | 0.74.6   |
| @react-navigation/bottom-tabs    | 7.2.0    |
| @react-navigation/native         | ^7.0.14  |
| @react-navigation/native-stack   | 7.2.0    |
| react-native-screens             | ^4.4.0   |
| react-native-reanimated          | 3.16.6   |
| react-native-gesture-handler     | 2.21.2   |
| react-native-pager-view          | ^6.6.1   |

**Comment by pizzascott** [comment]
Facing the same issue on IOS.

**Comment by pizzascott** [comment]
This is causing Pizzahuts app to freeze on IOS on IOS 18 devices and simulators.

**Comment by pizzascott** [comment]
Does anyone have a work around?

**Comment by Mokhtar25** [comment]
> Does anyone have a work around?

Use push, and dismiss. Instead of navigate

**Comment by kkafar** [comment]
removing the `getId` prop from reproducer fixes the issue. `react-native-screens` does not have any `getId` related logic. Are there any premises that this is `react-native-screens` issue? @marklawlor

**Comment by kkafar** [comment]
Okay, I have high level grasp of the issue mechanism now. 

Let's have a following stack of screens: `A B` and let's set `getId` prop for both screens with constant values (not depending on route params).

Now, in `react-navigation@v7`, `navigate(A)` instead of popping the `B`, will **reshuffle** screens on the stack, to achieve the state `B A`. 
When `getId` is not present this will work fine, because "new navigate" will just push a brand new screen `A`, instead of navigating the the one already on the stack, so the resulting stack state would be `A B A`.

In previous version of `react-navigation` the `navigate(A)` call would just pop `B` and "navigate to the screen already on stack as the method name suggests", which would result in stack state: `A`. 

Now, the issue arises because reshuffling the screens on stack is not really supported & it seems that it has not been the case for a longer while, as it was not needed. Moreover, the crash that happens (and e.g. causes the header to disappear) suggests that this is due to asynchronous way we do the updates - which won't be easily changed. 

## Immediate solution

use `navigateDeprecated` instead of `navigate` in your apps

## Proper solution 

One of:

* restore original behaviour of `navigate` from before `react-navigation@v7`,
* change the behaviour of `navigate` for `native-stack` only,
* rewrite container update logic of screens - dunno if that's feasible - we do it in asynchronous way for a reason.

**Comment by satya164** [comment]
@kkafar this behavior now being default with `navigate` only makes it easier to see the problem, but it's not the only way to surface the issue (e.g. you can also have this issue with `reset` or other actions - in v6 it can happen when using `push` and `getId`) so changing it will only make the issue less common - but not fix it. it's fundamental to how react navigation works and declarative nature of react.

from native perspective, is it not possible to take the same view containing the screens and render it in a new screen if it was reordered?

**Comment by kkafar** [comment]
I haven't debugged it to very bottom, because the interaction between react-native's native mounting-stage code & Android Fragment transactions we use is quite complex, but the issue arises due to following:

1. Having stack view `S` with two children `A B`
2. UI block 1: React removes B from S,
3. UI block 1: we schedule removal of B from S on the UI queue (block 2),
4. UI block 1: React inserts B at index 0 into S,
5. UI block 1: we schedule removal of A, insertion of B and insertion of A on the UI queue (block 3)
6. block 2 executes
7. block 3 executes

The issue appears at point 4 - react tries to insert B, however it has been not yet effectively detached and still has a parent (still attached to S), because we didn't perform the update - we've just scheduled it for later execution. 

Idk what would be technical solution here yet. I'll start discussion internally on how we could start supporting such "reshuffling". 

I still wonder whether allowing for screen reshuffling in stack-based navigators is ok. From my current perspective this seems against the 'stack' logic. I wonder what are the use cases that people might consciously choose reshuffling the screens in stack. **My guess** is that most of the time this decision is not deliberate.

**Comment by pizzascott** [comment]
What package is navigateDeprecated in? I can't see it under CommonActions?

**Comment by kkafar** [comment]
@pizzascott its on `navigation` object in `react-navigation`

**Comment by pizzascott** [comment]
Ah I think we are on an older version so already using deprecated. Which is why android is fine for our app, but IOS is breaking. 

Still haven’t found a work around and seems to happen when changing tab index also.

**Comment by pizzascott** [comment]
Temp fix for IOS is to use `StackActions.replace`

**Comment by pizzascott** [comment]
Just an update on our situation. 

We are on "react-native-screens": "~3.29.0" 

We experienced a bug that switching to a certain tab would freeze our app on IOS only. 

We fixed it by switching to .replace instead of .navigate.

**Comment by islamouzou** [comment]
The same problem happens to me using expo-router , it’s a game stopper. Using tab with a stack for each tab . When i navigate back and forth within the stack / to different stacks , the stack becomes blank . It gets dismissed somehow. One time touchable opacity within the stack became unclickable . I tried a mix of router.push , router.replace , router.navigate . I ended up using push but it didn’t fix all the problem . Tho it happens less now . I am on Android .

**Comment by kkafar** [comment]
I just wanna update that I'm looking into the issue. However current approach is to forbid certain kinds of navigation patters as they do not make much sense on stack-based navigator. I'm building the case 😅

**Comment by demmyhonore** [comment]
I am a bit worried that this issue is not getting more priority. :worried:

It really looks bad on Expo if solid navigating cannot be guaranteed. Navigating between screens is such a core feature to any app. 

We will release our Expo app pretty soon to production and I am not sure how to explain this to stakeholders that our navigating is able to crash.

Reading the previous comments there is not really a solid workaround yet? :sweat_smile:

**Comment by tmoran-stenoa** [comment]
I don't know if the cause is the same, but I'm having this issue and I'm not even using `getId`, just `navigation.push()` onto a screen with `presentation: "modal"`. If I repeatedly open and close the screen quickly on iOS (18.4), the app eventually crashes with the `Modally presented controllers are being reshuffled, this is not allowed` error.

Interestingly, if I replace `navigation.push()` with `navigation.navigate()`, the issue seems to go away.

|Package|Version|
|-|-|
| `react-native` | `0.78.2` |
| `@react-navigation/native` | `7.1.5` |
| `@react-navigation/native-stack` | `7.3.9` |
| `react-native-screens` | `4.10.0` |

**Comment by ethandpowers** [comment]
Running into this issue as well.  Is their going to be addressed?

**Comment by DylanWard14** [comment]
Running into this issue using Expo Router also.

**Comment by marklawlor** [comment]
This issue should be resolved in SDK 53 for Expo Router. If you are still experiencing this issue after upgrading, please create a new issue on the [expo repo](https://github.com/expo/expo) as it is most likely not related to this issue.

**Comment by BamMironov** [comment]
@marklawlor it has not been resolved in SDK 53, it's still there. Just tested it (expo 53.0.9). 
There is an **open** issue assigned to you https://github.com/expo/expo/issues/33658#issuecomment-2878154551 (from December 13 2024) which is essentially the same bug.
I wonder when it gets prioritized as this is a blocker for anyone who want to use New Architecture.

**Comment by sivadass** [comment]
Anybody have solid workaround for this in Expo SDK 52?

**Comment by ahmadsakur** [comment]
jumping to start RN for a day and already found this kind of bug LMAO 😺

**Comment by dannyBies** [comment]
This issue has been open for a while now. A significant amount of my users experience these crashes on Android. 

I appreciate there are other issues and features to work on, but this is one of the most upvoted issues in the repo showing the probability of this happening and severity of this issue to be relatively high.

Is there any chance of getting this looked into in the short term?

**Comment by demmyhonore** [comment]
I managed to solve this issue in our Expo app by preventing unnecessary navigation stack buildup. It seems that Expo (or React Native) doesn't always handle a growing navigation stack gracefully. 🤔 

At first, I was using `Router.navigate()` for everything (including navigation between the bottom tabs) under the assumption that this was fine, since users could then press back to return to previous screens. But this ends up continuously adding new entries to the navigation history, which causes the stack to grow indefinitely (and Expo or React Native applying potential erroneous internal stack management to it?).

Eventually, I realised that users don't expect to press "back" after switching tabs. So I switched to using `Router.replace()` when handling tab navigation. That way, the navigation stack stays much cleaner and doesn't bloat over time. This fixed it for us. 👍🏼

**Comment by eeshankeni** [comment]
This is why I absolutely loath react native, especially on android. Write once, debug everywhere.
I have a simple list of profiles and a dynamic route [id], every third router.push on the list results in a blank screen. Pressing the tab button to return back briefly shows the missing screen for a split second before going back. Next 2 navigations works fine. This is such an absolutely dumb easy use case I cant even imagine the kind of rubbish that'll happen as the app gets more complicated.

I used to use react navigation 2 years ago and for all its complexity, I've never had these kinds of silly issues.

Edit: This is possibly the biggest piece of turd bug I've seen yet, and mind you I've seen so so many over the years. Somehow adding a StatusBar from expo status bar made the screen appear. Finding this thing was a complete fluke seriously what the actual $$$ guys :/

**Comment by C0wnuts** [comment]
Hi everyone, I’m also running into this bug on both iOS and Android (Occurs much more frequently on iOS). 

Exactly as @eeshankeni described: after several navigations, the page content randomly turns blank (layout content is still visible), then briefly flashes before switching to the next page.
In my case it only happens with the tabBar (expo-router) using navigation.navigate.

Any updates or new workarounds before an official fix?

New edit : I found a workaround that solved the problem: I removed the transition animation between pages when navigating via the tab bar.

**Comment by Sascha195** [comment]
I'm also seeing this on Android quite often. Stack points to com.swmansion.rnscreens.ScreenStackHeaderConfig.onUpdate (~line 339): IllegalStateException: The specified child already has a parent.

These are the deps I'm using (newArch is enabled):
"react-native": "0.79.5",
"expo": "53.0.20",
"react-native-screens": "4.16.0",
"@react-navigation/native": "7.1.17",
"@react-navigation/native-stack": "7.3.26"

I hope there will be a fix soon since it affects many of our users.

Stacktrace:
```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:6065)
       at android.view.ViewGroup.addView(ViewGroup.java:5884)
       at android.view.ViewGroup.addView(ViewGroup.java:5824)
       at android.view.ViewGroup.addView(ViewGroup.java:5796)
       at com.swmansion.rnscreens.ScreenStackHeaderConfig.onUpdate(ScreenStackHeaderConfig.kt:339)
       at com.swmansion.rnscreens.ScreenStackHeaderConfig.onAttachedToWindow(ScreenStackHeaderConfig.kt:156)
       at android.view.View.dispatchAttachedToWindow(View.java:22010)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4291)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
       at android.view.ViewGroup.addView(ViewGroup.java:5884)
       at android.view.ViewGroup.addView(ViewGroup.java:5824)
       at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:901)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:585)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2065)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
       at com.swmansion.rnscreens.ScreenStack.onUpdate(ScreenStack.kt:282)
       at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.kt:367)
       at com.swmansion.rnscreens.ScreenContainer.onScreenChanged$lambda$8(ScreenContainer.kt:350)
       at com.swmansion.rnscreens.ScreenContainer.$r8$lambda$_XN8QBWatVwLAw6wNpLgWT68aTo()
       at com.swmansion.rnscreens.ScreenContainer$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.kt:20)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by ajanuar** [comment]
Hi @kkafar , any updates on this issue?

**Comment by kkafar** [comment]
Is there an reproduction using plain screens (no expo involved)?

Do you by any chance use view recycling on Android?

**Comment by satya164** [comment]
I had a repro in my issue https://github.com/software-mansion/react-native-screens/issues/2575

**Comment by williamliangwl** [comment]
Hi @kkafar , any update on this? We have tried to use `navigateDeprecated` but still seeing the error logged in our Crashlytics

**Comment by QQizi** [comment]
I have this issue of white screen when I switch between tabs. Still no fixe ?

**Comment by erickweyunga** [comment]
## Workaround Confirmed: Using `router.replace()` instead of `router.push()`

I can confirm that replacing `router.push()` with `router.replace()` resolves the issue on my end when navigating between screens in Expo Router (React Navigation v7).

### My Setup
- **expo-router**: `~5.1.4`
- **react-native-screens**: `~4.11.1`
- **@react-navigation/native**: `^7.0.14`
- **Platform**: Testing on both iOS and Android (funny enough this issue never happened on IOS)

### What I Changed
In my case, I was experiencing the exact symptoms described in this issue when navigating from my transactions list screen to a withdraw flow screen. The navigation was triggered via:

```tsx
// Before (causing issues)
router.push("/transactions/withdraw");

// After (working fine)
router.replace("/transactions/withdraw");
```

Additional Fix
I also standardized my animation settings by removing conflicting animation configurations in my nested Stack navigators (was mixing `animation: "none"`, `animation: "fade"`, and `animation: "fade_from_bottom"` in parent and child screens). Removing these conflicts and letting the default animations run seems to help as well.

While this workaround solves my immediate problem, I agree this isn't an ideal long-term solution since it changes the navigation behavior semantically.

**Comment by mmplanet** [comment]
I have the same bug @eeshankeni described. His language was not the best, but I don't get why he has gotten 6 downvotes for pointing out a very valid bug. It's an extremely frustrating bug. I have tried router.push, .navigate and .replace and I see no changes whatsoever when it comes to this bug's behaviour. 

LE: disabling the animation solves the bug. This is not a solution, just an observation.
LLE: This is happening on both iOS and Android, with .replace, .push and .navigate.

```
<Tabs.Screen
          name="screen/[id]"
          options={{
            href: null,
            animation: "none",
          }}
        />
```

**Comment by mmplanet** [comment]
I've found a "fix". While debugging this, I found a very weird behaviour. The bug is not happening anymore if I add a console log here:
node_modules/@react-navigation/bottom-tabs/lib/module/views/BottomTabView.js:98
i.e.
```
let spec = transitionSpec;
                if (route.key !== previousRouteKey && route.key !== focusedRouteKey) {
                    console.log("skipping animation");
                    // Don't animate if the screen is not previous one or new one
                    // This will avoid flicker for screens not involved in the transition
                    spec = NAMED_TRANSITIONS_PRESETS.none.transitionSpec;
                }
```


@eeshankeni @C0wnuts can you please try on your end and see if this solves the issue for you?

**Comment by mmplanet** [comment]
I've used AI to generate a fix for this and after a few back n forths, I think I nailed it.
Apply this expo plugin:

```
const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

module.exports = function withPatchBottomTabs(config) {
  return withDangerousMod(config, [
    "ios",
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        "..",
        "node_modules",
        "@react-navigation",
        "bottom-tabs",
        "lib",
        "module",
        "views",
        "BottomTabView.js",
      );

      if (fs.existsSync(filePath)) {
        let content = fs.readFileSync(filePath, "utf8");

        // Find the .start callback and inject the fix
        const searchPattern = /\.start\(\(\{\s*finished\s*\}\) => \{/;
        const replacement = `.start(({ finished }) => {
                // Patch: Force animation values to final state
                state.routes.forEach((route, index) => {
                    if (index !== state.index) {
                        tabAnims[route.key].setValue(1);
                    } else {
                        tabAnims[route.key].setValue(0);
                    }
                });
                `;

        if (content.match(searchPattern) && !content.includes("// Patch: Force animation values")) {
          content = content.replace(searchPattern, replacement);
          fs.writeFileSync(filePath, content, "utf8");
          console.log("✅ Applied bottom-tabs animation patch");
        }
      }

      return config;
    },
  ]);
};

```

**Comment by florianck** [comment]
I just have the same issue. kind of random pages simply always had a white screen but no error at all. In Expo Go on my Android phone. Others sometimes (like raceconditions). 

what i changed in my RootLayout

`function RootNavigator() {
  useAuthAndOnboardingRedirect();

  return <Stack screenOptions={{ animation: 'none', headerShown: false }} />;
}
`

Turning of the animations did the job.

**Comment by gabrielsalvi** [comment]
Disabling the animation shouldn’t be necessary. Is there a fix to this in progress?

**Comment by andreilupu-plt** [comment]
We've started facing the same crashes as @Sascha195 reported above once we did upgrade of expo from 52 to 53 along with screens library an other depedecnies + newArch enabled.


```json
{
  "expo": "~53.0.27",
  "react": "19.0.0",
  "react-native": "0.79.6",
  "expo-router": "~5.1.11",
  "react-native-screens": "~4.11.1"
  "react-native-reanimated": "~3.17.4",
}
```

Stack trace: 
```
          Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5539)
       at android.view.ViewGroup.addView(ViewGroup.java:5358)
       at android.view.ViewGroup.addView(ViewGroup.java:5298)
       at android.view.ViewGroup.addView(ViewGroup.java:5270)
       at com.swmansion.rnscreens.ScreenStackHeaderConfig.onUpdate(ScreenStackHeaderConfig.kt:339)
       at com.swmansion.rnscreens.ScreenStackHeaderConfig.onAttachedToWindow(ScreenStackHeaderConfig.kt:156)
       at android.view.View.dispatchAttachedToWindow(View.java:24320)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3745)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3752)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3752)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5582)
       at android.view.ViewGroup.addView(ViewGroup.java:5358)
       at android.view.ViewGroup.addView(ViewGroup.java:5298)
       at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:901)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:585)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2214)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2115)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:2002)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
       at com.swmansion.rnscreens.ScreenStack.onUpdate(ScreenStack.kt:262)
       at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.kt:359)
       at com.swmansion.rnscreens.ScreenContainer.onScreenChanged$lambda$7(ScreenContainer.kt:342)
       at com.swmansion.rnscreens.ScreenContainer.$r8$lambda$BKP9nn15fXkNMeJuCPogdGvGxQY()
       at com.swmansion.rnscreens.ScreenContainer$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:995)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.kt:20)
       at android.os.Looper.loopOnce(Looper.java:273)
       at android.os.Looper.loop(Looper.java:363)
       at android.app.ActivityThread.main(ActivityThread.java:10060)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

Unfortunately, we haven’t been able to reliably reproduce the issue.I noticed a [draft PR](https://github.com/software-mansion/react-native-screens/pull/3777) was opened some time ago that seems related. However, there haven’t been any recent updates, and it’s unclear whether it would resolve this problem.

**Comment by fracico-tech** [comment]
Same issue:
```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5327)
       at android.view.ViewGroup.addView(ViewGroup.java:5156)
       at android.view.ViewGroup.addView(ViewGroup.java:5096)
       at android.view.ViewGroup.addView(ViewGroup.java:5068)
       at com.swmansion.rnscreens.ScreenStackHeaderConfig.onUpdate(ScreenStackHeaderConfig.kt:341)
       at com.swmansion.rnscreens.ScreenStackHeaderConfigViewManager.onAfterUpdateTransaction(ScreenStackHeaderConfigViewManager.kt:91)
       at com.swmansion.rnscreens.ScreenStackHeaderConfigViewManager.onAfterUpdateTransaction(ScreenStackHeaderConfigViewManager.kt:22)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:104)
       at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.kt:627)
       at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateProps(SurfaceMountingManager.kt:597)
       at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.kt:127)
       at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.kt:340)
       at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.kt:246)
       at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.kt:93)
       at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1528)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.kt:42)
       at com.facebook.react.modules.core.ReactChoreographer.frameCallback$lambda$1(ReactChoreographer.kt:59)
       at com.facebook.react.modules.core.ReactChoreographer.$r8$lambda$nSkFhrr5T7rop_XKwzlLov4NLLw()
       at com.facebook.react.modules.core.ReactChoreographer$$ExternalSyntheticLambda0.doFrame(D8$$SyntheticClass)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1728)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1739)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1255)
       at android.view.Choreographer.doFrame(Choreographer.java:1145)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1693)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:249)
       at android.os.Looper.loop(Looper.java:337)
       at android.app.ActivityThread.main(ActivityThread.java:9593)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by gabrielBatistella** [comment]
### Workaround for original stack reorder bug, as tracked by [issue 2575](https://github.com/software-mansion/react-native-screens/issues/2575)

Hey everyone!

I've written a [Medium article](https://medium.com/profusion-engineering/issues-with-unique-screens-on-react-navigation-when-getid-meets-native-stack-099eff7ae27f) regarding this issue and a workaround I implemented in my project.
The article also contains a repro to the original issue with no expo framework.

Granted, I notice this thread has evolved a bit and also includes some other scenarios where the bug can pop up, apart from the original one that was discussed in my article. So take my suggested solution for what it is, a workaround, not a final fix.

Still, I hope it can help some of you that might be in the same situation we were
