### ISSUE TITLE
[Android] Issue with react-navigation mode modal

### ISSUE THREAD

**Issue by AlexSmirnov9107** [software-mansion/react-native-screens#290]
Android
"react-native-screens": "^2.0.0-alpha.27",

`
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.fragment.app.FragmentManager.removeOnBackStackChangedListener(androidx.fragment.app.FragmentManager$OnBackStackChangedListener)' on a null object reference
        at com.swmansion.rnscreens.ScreenStack.onDetachedFromWindow(ScreenStack.java:73)
        at android.view.View.dispatchDetachedFromWindow(View.java:17524)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3695)
        at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5457)
        at android.view.ViewGroup.removeAllViews(ViewGroup.java:5403)
        at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow(ScreenContainer.java:256)
        at android.view.View.dispatchDetachedFromWindow(View.java:17524)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3695)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3695)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3695)
        at android.view.ViewGroup.endViewTransition(ViewGroup.java:6820)
        at com.swmansion.rnscreens.ScreenContainer.endViewTransition(ScreenContainer.java:124)
        at androidx.fragment.app.FragmentManagerImpl$EndViewTransitionAnimation.run(FragmentManagerImpl.java:3478)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
`

**Comment by panteleymonchuk** [comment]
Any solutions?

**Comment by kmagiera** [comment]
Looks like a fix for this crash landed in alpha.28 -> https://github.com/software-mansion/react-native-screens/commit/1c7ebeba39a3d26437a89a1c929d68cec0257227
