### ISSUE TITLE
Crash on Android with react-navigation stack

### ISSUE THREAD

**Issue by mtt87** [software-mansion/react-native-screens#309]
When I navigate to this specific screen the app is crashing.
It works fine on iOS and it works fine if I comment out `enableScreens()` and not use `react-native-screens`

It's a pretty standard screen, apollo hooks + `SectionList` and some `Text` `View` `TouchableOpacity` (from `react-native-gesture-handler`)

Here is the log collected by Sentry, is there anything I can do to debug and help finding the root cause?
```
java.lang.IllegalStateException: Fragment already added: ScreenFragment{e9e00a9 (89d81b03-c200-4966-881c-38bb9e88da42) id=0x175}
    at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1379)
    at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:399)
    at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
    at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
    at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
    at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
    at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by mtt87** [comment]
To help debug I just removed everything in that screen and I'm just doing
```jsx
function BrokenScreen() {
  return <View />
}
```

Seems somehow related to react navigation, I have this structure
```jsx
  const MainAppStack = createStackNavigator(
    {
      Tabs: {
        screen: Tabs,
        navigationOptions: {
          animationEnabled: false,
        },
      },
      BrokenScreen1,
      BrokenScreen2,
    },
    {
      defaultNavigationOptions: {
        headerShown: false,
        cardStyle: {
          backgroundColor: 'white',
        },
      },
    },
  );
```

And when I navigate from `Tabs` to one of the other screens the app crashes with the error above.
I'm using the standard `navigation.navigate('BrokenScreen1')`

**Comment by luutruong** [comment]
I have same with this issue.

**Comment by kmagiera** [comment]
Thanks @mtt87 for reporting, any chance you could share a complete app/example I can use to reproduce this problem?

**Comment by mtt87** [comment]
I've tried to start a new project from scratch, added react-navigation and all the dependencies, added stack and tabs, created a similar navigation setup but it doesn't crash so I'll need to slowly add more things until it breaks to pin down what's causing this.

**Comment by deng-yc** [comment]
+1

**Comment by adamczyk777** [comment]
@kmagiera This is the same issue I have. At least callstack is almost the same.

**Comment by Preeternal** [comment]
I have the same behaviour when I am trying to turn on **toggle inspector** in my simulator:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.*, PID: 4671
    java.lang.IllegalStateException: Fragment already added: ScreenFragment{f2ad48d (977dc763-f4e6-45fd-8225-8f20a879808b) id=0x3f5}
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1379)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:399)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by alimek** [comment]
just updated to latest `react-navigation` v4 + latest `react-native-screens` + `react-navigation-stack` and my android app is crashing with this when i trying to open `Toggle Inspector`

**Comment by DovletAmanov** [comment]
Same issue with react-navigation v5 and react-native-screens v2.0.0-beta.2
Happens when going back to previous screen

**Comment by muhammadwafa** [comment]
I think you are using stack navigator and this is not necessary for that if you are using `native-stack` then you can use it.

**Comment by psloboda** [comment]
+1

**Comment by kmagiera** [comment]
I hear from @adamczyk777 that this crash no longer occurs on the most recent release (2.0.0-beta.6). As I don't see any repro case here I could use to verify I can only ask whoever reported the crash here if you still get it on beta.6. In case you do please comment below or start a new issue with a repro scenario.

**Comment by alimek** [comment]
@kmagiera 

```
2020-02-18 16:11:51.104 14862-14862/com.halo.fitness E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.halo.fitness, PID: 14862
    java.lang.ClassCastException: com.bumptech.glide.manager.SupportRequestManagerFragment cannot be cast to com.swmansion.rnscreens.ScreenFragment
        at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.java:255)
        at com.swmansion.rnscreens.ScreenContainer.updateIfNeeded(ScreenContainer.java:238)
        at com.swmansion.rnscreens.ScreenContainer.access$000(ScreenContainer.java:23)
        at com.swmansion.rnscreens.ScreenContainer$1.doFrame(ScreenContainer.java:38)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
could this be still related to fix?

**Comment by mtt87** [comment]
@kmagiera on my end I just tried and it seems to be fine 😄 well done 🎉 
Curious to what was?

**Comment by kmagiera** [comment]
Great to hear @mtt87 

@alimek – as for the crash I don't think it is related but I can understand what other change might've caused that crash. Would be great if you could prepare a repro case for that crash and start a new issue as I believe that one is not related.

**Comment by alimek** [comment]
> @alimek – as for the crash I don't think it is related but I can understand what other change might've caused that crash. Would be great if you could prepare a repro case for that crash and start a new issue as I believe that one is not related.

It is happening when I am closing modal screen, but not on every screen. I will try to check why it crashes on my side first and then try to create repo. 👍 cheers

**Comment by Flouwrian** [comment]
@kmagiera i´m having the same error, when i try to use the back button in the stack header bar. I´m currently migrating from react-navigation 4 to react-navigation 5 and everythings working nice just this is bothering me.

**Comment by tomffee** [comment]
what helped us was actually removing `useScreens` method while using android platform for now.

```
import {useScreens} from 'react-native-screens';
// TODO: Remove condition after react-navigation this issue is fixed
if (Platform.OS === 'ios') {
  useScreens();
}
```

**Comment by fangasvsass** [comment]
why close this issue  android crash 0.62.2 android react navigation5

**Comment by fangasvsass** [comment]
> Same issue with react-navigation v5 and react-native-screens v2.0.0-beta.2
> Happens when going back to previous screen
 any update?

**Comment by RnbWd** [comment]
I'm seeing a similar error in the crash reports on google console for apps in production, maybe I should disable `useScreens()` on android. Here are my library versions:

```
"@react-navigation/native": "^5.6.1",
"@react-navigation/stack": "^5.6.2",
"react-native-screens": "^2.9.0",
```

I'm using the `@react-navigation/stack` navigator, not the native stack navigator

**Comment by beqramo** [comment]
@WoLewicki  please have a look.

it happens for me on `` goBack() `` but not a first time, it happens when I repeat this action frequently  on the same screen, so navigate to this screen, go back and again.
I see this error only on android release

**Comment by WoLewicki** [comment]
@beqramo can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by Hardik500** [comment]
Here is a reproducable repo: https://github.com/Hardik500/madri
The issue still exists, whenever I go to the next screen in build apk, the App crashes.
Works great on development mode.

**Comment by WoLewicki** [comment]
@Hardik500 the app is too big to easily catch the problem. Please provide a minimal reproducible example in a form of a e.g. snack so everybody can elaborate on it.

**Comment by Hardik500** [comment]
Sorry for the late reply, I was debugging the code and found out the issue was not with navigation but rather the image component, so had to replace that with a different library.

**Comment by mtx62** [comment]
confirm that you used 

```
import { enableScreens } from 'react-native-screens';

enableScreens(false);
```

**Comment by NoahMLoomis** [comment]
My issue was the same, the app would work fine in development in an emulator, but when i built an APK and downloaded it onto the emulator, it crashed instantly. 

This is because when creating my Stack to navigate, I was doing the following:

```
import { createStackNavigator } from '@react-navigation/stack'

const Stack = createStackNavigator()
```
Instead, what I should've been importing was the following:
```
import { createNativeStackNavigator  } from '@react-navigation/native-stack';

const Stack = createNativeStackNavigator()

```
It's a small error, and it didn't break in local development for some reason, only in build

**Comment by antoinedesp** [comment]
For those still having this random issue when navigating to specific screens, you may want to use following at top of your root component :

```
if (Platform.OS === 'android') {
	if (UIManager.setLayoutAnimationEnabledExperimental) {
		UIManager.setLayoutAnimationEnabledExperimental(false);
	}
}
```
