### ISSUE TITLE
[Android] AndroidRuntime: FATAL EXCEPTION

### ISSUE THREAD

**Issue by alimek** [software-mansion/react-native-screens#343]
Stack trace: 

```
2020-02-18 16:11:51.104 14862-14862/xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx, PID: 14862
    java.lang.ClassCastException: com.bumptech.glide.manager.SupportRequestManagerFragment cannot be cast to com.swmansion.rnscreens.ScreenFragment
        at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.java:255)
        at com.swmansion.rnscreens.ScreenContainer.updateIfNeeded(ScreenContainer.java:238)
        at com.swmansion.rnscreens.ScreenContainer.access$000(ScreenContainer.java:23)
        at com.swmansion.rnscreens.ScreenContainer$1.doFrame(ScreenContainer.java:38)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Versions:
```
"react-navigation": "^4.0.10",
 "react-navigation-stack": "^2.1.1",
"react-native-screens": "^2.0.0-beta.6",
```

It is crashing when I am closing Modal Screen, trying to investigate why its happening only for one screen in my app at the moment.

Will update this post once i have some more information.

**Comment by alimek** [comment]
update:

Problem is here: https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java#L255

`orphanedAry` sometimes has extra `SupportRequestManagerFragment` object and then casting this to `ScreenFragment` is crashing app.

Still trying to guess what is causing this problem in the app, because i have the same screen sometimes open with extra props, for one use case it works fine and i can't see object`SupportRequestManagerFragment` , but then another use case adding this object.

<img width="1009" alt="Screenshot 2020-02-18 at 18 54 09" src="https://user-images.githubusercontent.com/4248465/74768263-2d72a100-5280-11ea-98dd-77df928cf5be.png">

After small change I have managed to at least not crash the app, but not sure if this `SupportRequestManagerFragment` object can stay there forever. My Android knowledge is not good enough to answer that question :) 

@kmagiera please check https://github.com/software-mansion/react-native-screens/pull/344

**Comment by Jekiwijaya** [comment]
related to #339
