### ISSUE TITLE
Java exception: java.lang.ClassCastException: com.facebook.react.modules.dialog.AlertFragment cannot be cast to com.swmansion.rnscreens.ScreenFragment

### ISSUE THREAD

**Issue by davewthompson** [software-mansion/react-native-screens#382]
The following exception is thrown when I show an Alert using 'Alert.alert' in a React Native app; the alert appears, but then a second or so later the following exception is thrown: 

`2020-02-25 10:42:55.340 11170-11170/[redacted] E/unknown:ReactNative: Exception in native call
    java.lang.ClassCastException: com.facebook.react.modules.dialog.AlertFragment cannot be cast to com.swmansion.rnscreens.ScreenFragment
        at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.java:255)
        at com.swmansion.rnscreens.ScreenContainer.updateIfNeeded(ScreenContainer.java:238)
        at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.java:216)
        at android.view.View.dispatchAttachedToWindow(View.java:20018)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3589)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5302)
        at android.view.ViewGroup.addView(ViewGroup.java:5090)
        at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:453)
        at android.view.ViewGroup.addView(ViewGroup.java:5030)
        at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:355)
        at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:37)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:512)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:205)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:984)
        at android.view.Choreographer.doCallbacks(Choreographer.java:764)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

OS: macOS Catalina
Environment:
- "react": "16.9.0",
- "react-native": "0.61.5",
- "react-native-screens": "^2.0.0-beta.6",
- "@react-navigation/native": "^5.0.5"

**Comment by kmagiera** [comment]
I believe this is fixed as of #344 which landed in beta.8
