### ISSUE TITLE
Could not resolve androidx.cardview:cardview:1.0.0.

### ISSUE THREAD

**Issue by AlissonBlaas** [software-mansion/react-native-screens#452]
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
[Fatal Error] cardview-1.0.0.pom:2:1: O conte�do n�o � permitido no pr�logo.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.cardview:cardview:1.0.0.
     Required by:
         project :app
         project :app > project :react-native-screens > com.google.android.material:material:1.1.0
      > Could not resolve androidx.cardview:cardview:1.0.0.
         > Could not parse POM https://dl.google.com/dl/android/maven2/androidx/cardview/cardview/1.0.0/cardview-1.0.0.pom     
            > O conte�do n�o � permitido no pr�logo.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan 
to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
[Fatal Error] cardview-1.0.0.pom:2:1: O conte�do n�o � permitido no pr�logo.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.cardview:cardview:1.0.0.
     Required by:
         project :app
         project :app > project :react-native-screens > com.google.android.material:material:1.1.0
      > Could not resolve androidx.cardview:cardview:1.0.0.
         > Could not parse POM https://dl.google.com/dl/android/maven2/androidx/cardview/cardview/1.0.0/cardview-1.0.0.pom     
            > O conte�do n�o � permitido no pr�logo.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan 
to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

    at makeError (C:\Users\Alisson Blaas\Desktop\bicofacil-app\bicofacil-app\node_modules\execa\index.js:174:9)
    at C:\Users\Alisson Blaas\Desktop\bicofacil-app\bicofacil-app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\Users\Alisson Blaas\Desktop\bicofacil-app\bicofacil-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\Alisson Blaas\Desktop\bicofacil-app\bicofacil-app\node_modules\@react-native-community\cli\build\index.js:186:9)
```

I try to do different thing and nothing works. Anyone can help me with that?

**Comment by WoLewicki** [comment]
Can you show your `build.gradle` file?

**Comment by AlissonBlaas** [comment]
> Can you show your `build.gradle` file?

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

**Comment by WoLewicki** [comment]
Can you try and build the Example app from `react-native-screens`?

**Comment by AlissonBlaas** [comment]
Thanks bro, sorry for delay! I fix that one.

i just clean build gradlew and react native cache and this is work fine

**Comment by Bageerapm** [comment]
Error:

ERROR: Failed to resolve: androidx.cardview:cardview:1.1.0
Show in Project Structure dialog
Affected Modules: app
