### ISSUE TITLE
2020-09-07 09:32:53.758 4298-4298/com.example.yndrlook E/AndroidRuntime: FATAL EXCEPTION: main     Process: com.example.yndrlook, PID: 4298     java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

### ISSUE THREAD

**Issue by yadvendrayadav123** [software-mansion/react-native-screens#625]
2020-09-07 09:32:53.758 4298-4298/com.example.yndrlook E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.yndrlook, PID: 4298
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here:                                       *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to add a valid App ID inside the AndroidManifest.                          *
    * Google Ad Manager publishers should follow instructions here:              *
    * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:6537)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6025)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5931)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here:                                       *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to add a valid App ID inside the AndroidManifest.                          *
    * Google Ad Manager publishers should follow instructions here:              *
    * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzza.attachInfo(com.google.android.gms:play-services-ads-lite@@19.3.0:33)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@19.3.0:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6532)
        	... 10 more

**Comment by WoLewicki** [comment]
I cannot see anything related to `react-native-screens` here. How can I help you with this issue?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
