### ISSUE TITLE
FragmentManager has been destroyed

### ISSUE THREAD

**Issue by melkayam92** [software-mansion/react-native-screens#751]
## Description

I can't reproduce it, but it happened 1000 times in the last month in production. (Sentry and Google Console crash report)

This is the stack trace:

java.lang.IllegalStateException: FragmentManager has been destroyed
    at androidx.fragment.app.l.a
    at androidx.fragment.app.l.a
    at com.swmansion.rnscreens.g.onDetachedFromWindow
    at android.view.View.dispatchDetachedFromWindow(View.java:18679)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3886)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5640)
    at android.view.ViewGroup.removeAllViews(ViewGroup.java:5586)
    at com.swmansion.rnscreens.d.onDetachedFromWindow
    at android.view.View.dispatchDetachedFromWindow(View.java:18679)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3886)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3878)
    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5432)
    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5403)
    at android.view.ViewGroup.removeView(ViewGroup.java:5334)
    at com.swmansion.rnscreens.d.removeView
    at androidx.fragment.app.l.a
    at androidx.fragment.app.l.j
    at androidx.fragment.app.l.i
    at androidx.fragment.app.l.a
    at androidx.fragment.app.l.b
    at androidx.fragment.app.l.c
    at androidx.fragment.app.l.c
    at androidx.fragment.app.l$d.run
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

## Steps To Reproduce

Can't reproduce it, tried to kill activity and all that but didn't reproduce.. (I did put the onCreate(null) )

## Snack or minimal code example

I'm using a nested navigator

The HomeStack is the native

```
function HomeNavigator() {
  return (
        <HomeStack.Navigator screenOptions={{ headerShown: false }}>
          <HomeStack.Screen
            options={{
              animationEnabled: false,
              stackAnimation: 'none',
            }}
            name={"Test"}
            component={TestScreen}
          />
          <HomeStack.Screen
            options={{
              animationEnabled: false,
              stackAnimation: 'none',
              drawerLockMode: 'locked-closed',
            }}
            name="Test2"
            component={Test2}
          />
        </HomeStack.Navigator>
  );
}

function DrawerNavigator({ currentScreen }) {
  return (
    <Drawer.Navigator
      drawerType="slide"
      backBehavior="none"
      drawerContent={props => {
        return <DrawerContent {...props} />;
      }}
    >
      <Drawer.Screen
        name={"Home"}
        component={HomeNavigator}
      />
    </Drawer.Navigator>
  );
} 

```

## Package versions

<!--
- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 2.16.1

**Comment by WoLewicki** [comment]
Can you post the whole stack trace with the exact line and file in `react-native-screens`, where the exception occurs? And could you post a runnable reproduction in 
[TestExample](https://github.com/software-mansion/react-native-screens/tree/master/TestsExample) ? Also, you didn't provide the packages versions.

**Comment by diego-paired** [comment]
We're experiencing the same issue, here's a stack trace with line numbers (v2.16.1):

```java.lang.IllegalStateException: 
  at androidx.fragment.app.FragmentManager.enqueueAction (FragmentManager.java:14)
  at androidx.fragment.app.FragmentManager.popBackStack (FragmentManager.java:7)
  at com.swmansion.rnscreens.ScreenStack.onDetachedFromWindow (ScreenStack.java:29)
  at android.view.View.dispatchDetachedFromWindow (View.java:21358)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4649)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4641)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4641)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4641)
  at android.view.ViewGroup.removeAllViewsInLayout (ViewGroup.java:6499)
  at android.view.ViewGroup.removeAllViews (ViewGroup.java:6445)
  at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow (ScreenContainer.java:34)
  at android.view.View.dispatchDetachedFromWindow (View.java:21358)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4649)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4641)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4641)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4641)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4641)
  at android.view.ViewGroup.endViewTransition (ViewGroup.java:8059)
  at com.swmansion.rnscreens.ScreenStack.endViewTransition (ScreenStack.java)
  at androidx.fragment.app.FragmentAnim$EndViewTransitionAnimation.run (FragmentAnim.java:21)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)```

**Comment by WoLewicki** [comment]
@diego-paired can you provide a reproduction of this? It is really hard to do anything about this without the crash being reproducible.

**Comment by anuragdadheech** [comment]
Reproducible on resuming the app with Do not keep activities enabled on android.

**Comment by WoLewicki** [comment]
@anuragdadheech can you provide a reproduction of this behavior?

**Comment by diego-paired** [comment]
The issue is happening quite frequently to our users and we can't reproduce it, is there any other information that would be useful?

![image](https://user-images.githubusercontent.com/55058765/107115408-72625f80-6864-11eb-8301-6212261e0b2f.png)
![image](https://user-images.githubusercontent.com/55058765/107115414-77bfaa00-6864-11eb-904f-9721dd5ef2c7.png)

```
java.lang.IllegalStateException: 
  at androidx.fragment.app.FragmentManager.enqueueAction (FragmentManager.java:14)
  at androidx.fragment.app.FragmentManager.popBackStack (FragmentManager.java:7)
  at com.swmansion.rnscreens.ScreenStack.onDetachedFromWindow (ScreenStack.java:29)
  at android.view.View.dispatchDetachedFromWindow (View.java:17567)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3775)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3767)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3767)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3767)
  at android.view.ViewGroup.removeAllViewsInLayout (ViewGroup.java:5527)
  at android.view.ViewGroup.removeAllViews (ViewGroup.java:5473)
  at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow (ScreenContainer.java:34)
  at android.view.View.dispatchDetachedFromWindow (View.java:17567)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3775)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3767)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3767)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3767)
  at android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:3767)
  at android.view.ViewGroup.endViewTransition (ViewGroup.java:6890)
  at com.swmansion.rnscreens.ScreenStack.endViewTransition (ScreenStack.java)
  at androidx.fragment.app.FragmentAnim$EndViewTransitionAnimation.run (FragmentAnim.java:21)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6680)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:810)
```

**Comment by WoLewicki** [comment]
Can you check if adding #805 fixes the crashes? From the stack trace it seems that the crash appears when you have a hierarchy of `native-stack` -> RN navigator with `react-native-screens` enabled (`stack` or `bottom-tabs` or `drawer`) -> `native-stack`. Then you change the screen in the top-most `native-stack`. I couldn't reproduce the crash unfortunately, but I believe the change from #805 should address it correctly. If you will be able to reproduce it with this information, please do.

**Comment by diego-paired** [comment]
> Can you check if adding #805 fixes the crashes? From the stack trace it seems that the crash appears when you have a hierarchy of `native-stack` -> RN navigator with `react-native-screens` enabled (`stack` or `bottom-tabs` or `drawer`) -> `native-stack`. Then you change the screen in the top-most `native-stack`. I couldn't reproduce the crash unfortunately, but I believe the change from #805 should address it correctly. If you will be able to reproduce it with this information, please do.

thanks, I'll patch-package the change, submit it in our next release and let you know of the results.

**Comment by melkayam92** [comment]
I can confirm that the fix did work for me, thanks alot

**Comment by carlosvpinto** [comment]
Tengo un error al intentar llamar un fragment por segunda vez, por favor ayudenme
![error ondestroy](https://user-images.githubusercontent.com/113474950/190887102-ae2e7d6d-e975-4237-bfd7-df8c269a6f0e.png)

**Comment by arulqb** [comment]
Check any memory leak is there or not
