### ISSUE TITLE
Crash on Android com.facebook.react.uimanager.IllegalViewOperationException: stack size 8MB

### ISSUE THREAD

**Issue by shamilovtim** [software-mansion/react-native-screens#910]
## Description

On Android devices when a user opens a heavy screen on our app and then clicks the back button to tap out of that heavy screen, the app hangs and after a minute or two the following exception is received. The crash only exists with Screens enabled on Android.

```
E/unknown:ReactNative: Exception in native call
    com.facebook.react.uimanager.IllegalViewOperationException: stack size 8MB
        at com.facebook.react.ReactRootView.handleException(ReactRootView.java:615)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:711)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21863)
        at android.view.View.updateDisplayListIfDirty(View.java:20733)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21863)
        at android.view.View.updateDisplayListIfDirty(View.java:20733)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:21863)
        at android.view.View.updateDisplayListIfDirty(View.java:20733)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.View.draw(View.java:21586)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4326)
        at android.view.View.updateDisplayListIfDirty(View.java:20719)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4507)
        at android.view.View.updateDisplayListIfDirty(View.java:20688)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4507)
        at android.view.View.updateDisplayListIfDirty(View.java:20688)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4507)
        at android.view.View.updateDisplayListIfDirty(View.java:20688)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4507)
        at android.view.View.updateDisplayListIfDirty(View.java:20688)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4507)
    	at android.view.View.updateDisplayListIfDirt
```

## Steps To Reproduce

1. On a Galaxy Note 9, Android 9, navigate to a heavy view with React Navigation.
2. Tap the back button
3. Receive the exception
4. Disable react native screens on Android 
5. Perform the steps again, crash does not reproduce

## Package versions

```
Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.3
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/admin/.rvm/gems/ruby-2.5.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.68 => 0.12.68
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ^0.16.1 => 0.16.1
     react-native-screns: 3.1.1
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: bare
```

**Comment by kacperkapusciak** [comment]
Could you provide a reproducible minimal code sample that we could test?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
