### ISSUE TITLE
`onDetachedFromWindow` triggered incorrectly

### ISSUE THREAD

**Issue by tien** [software-mansion/react-native-screens#913]
## Description

View that was part `ScreenContainer` received `onDetachedFromWindow` multiple times or before `onAttachedToWindow` (unlikely) causing [this](https://androidx.tech/artifacts/mediarouter/mediarouter/1.1.0-source/androidx/mediarouter/app/MediaRouteButton.java.html) Google Cast Button View to try and unregister an un-registered receiver. This doesn't happen when I set `enabledScreens(false)`

```
Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: androidx.mediarouter.app.MediaRouteButton$ConnectivityReceiver@82cf304
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1499)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1605)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:678)
       at androidx.mediarouter.app.MediaRouteButton$ConnectivityReceiver.unregisterReceiver(MediaRouteButton.java:871)
       at androidx.mediarouter.app.MediaRouteButton.onDetachedFromWindow(MediaRouteButton.java:562)
       at com.reactnative.googlecast.components.RNGoogleCastButtonManager$ColorableMediaRouteButton.onDetachedFromWindow(RNGoogleCastButtonManager.java:111)
       at android.view.View.dispatchDetachedFromWindow(View.java:21358)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:6499)
       at android.view.ViewGroup.removeAllViews(ViewGroup.java:6445)
       at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow(ScreenContainer.java:309)
       at android.view.View.dispatchDetachedFromWindow(View.java:21358)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4649)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6287)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6258)
       at android.view.ViewGroup.removeView(ViewGroup.java:6189)
       at com.swmansion.rnscreens.ScreenContainer.removeView(ScreenContainer.java:84)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1250)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1504)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2007)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 3.1.1

**Comment by WoLewicki** [comment]
Please provide a simple snack/repo with reproduction of this issue so we can work on it.

**Comment by YangJonghun** [comment]
@WoLewicki 

I reproduce this bug with [react-native-google-cast](https://github.com/react-native-google-cast/react-native-google-cast) and `react-navigation v5`

react-native-google-cast's [CastButton]() used `androidx.mediarouter.app.MediaRouteButton` internally
and it designed `onAttachedToWindow ` and `onDetachedFromWindow ` each called once.
but react-native-screens triggered `onDetachedFromWindow` call twice and it throw IllegalArgumentException with `onDetachedFromWindow`

detail)
I reproduce with stack indicated below
1) create `Screen(A)` include `CastButton`
2) create stack like this
`Stack(A)` -> `Bottom Tab` -> `Stack(B)`
3) insert `Screen(A)` within `Stack(B)`
4) open app and navigate to `Screen(A)`
5) tried to move other tab and crash(onDetachedFromWindow call twice)

this bug can't reproduce when Screen(A) into stack(A), bottom tab(B) or stack(B) with `detachInactiveScreens={false}`

**Comment by kacperkapusciak** [comment]
@YangJonghun
Great description but would you be so kind to provide a code snippet that we could copy-paste-and-run?
I'd like to avoid spending time implementing the description one again if you've already done it yourself.

Cheers

**Comment by WoLewicki** [comment]
Can you check if #985 fixes the issue? It should address the problem of double detach.

**Comment by YangJonghun** [comment]
@WoLewicki #985 fixed this issue
